-- phpMyAdmin SQL Dump
-- version 5.0.4
-- https://www.phpmyadmin.net/
--
-- Anamakine: 127.0.0.1
-- Üretim Zamanı: 09 Şub 2021, 15:54:46
-- Sunucu sürümü: 10.4.17-MariaDB
-- PHP Sürümü: 7.4.14

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Veritabanı: `myblog`
--

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `articles`
--

CREATE TABLE `articles` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `user_id` int(11) NOT NULL,
  `category_id` int(11) NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `article` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `img` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `hit` int(11) NOT NULL DEFAULT 0,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Tablo döküm verisi `articles`
--

INSERT INTO `articles` (`id`, `user_id`, `category_id`, `title`, `article`, `img`, `hit`, `slug`, `created_at`, `updated_at`) VALUES
(3, 3, 6, 'Est vitae labore id libero ad eligendi.', '<p>Et sint libero sint est sit quos dolores. Eos perferendis eius autem illo. Eaque aspernatur voluptatem ea. Eaque occaecati at sunt optio facere cum debitis. Aut a aspernatur assumenda natus. Iusto quo voluptatibus est pariatur dolores mollitia provident. Consectetur pariatur debitis culpa odio dignissimos id. Rerum dolorem amet itaque molestiae quod quibusdam consectetur est. Vero id et voluptatem. Est ipsam fuga et et nihil. Temporibus iste eius aut rerum. Cumque cumque odit et deleniti accusantium. Repudiandae molestias quis ducimus dolore rem. Pariatur soluta quia neque dolores quos nemo. Dolorem qui placeat eveniet sit. Cupiditate sit qui ratione voluptatem. Qui similique ut ipsa ipsam molestiae. Rerum autem in pariatur. Nihil qui cumque sunt quisquam quae. Ipsam qui vero laboriosam minus. Aliquam tenetur explicabo repudiandae deleniti ad ut dignissimos nemo. Ea odit corporis molestiae odio. Et temporibus voluptatum omnis ut cum hic. Architecto voluptas aut distinctio. Voluptatem fugit ullam dolorem officia perspiciatis nam est ad. Amet rerum ex cupiditate natus odit iste. Et ad earum veritatis blanditiis esse. Veritatis ad neque nesciunt eum hic. Et aut hic voluptas vero eveniet. Vel id porro unde expedita nihil. Et maiores minima et dolore veritatis. Consequuntur sunt et laudantium soluta. Id expedita quia a aspernatur quis et. Quasi assumenda aut asperiores laborum nisi fugiat ut eos. Perspiciatis dolores magnam voluptatem quia consequatur. Iusto perferendis voluptatem voluptatem suscipit. Quis vero explicabo magnam qui sed. Consequatur vel hic et non iste. Eos qui voluptatibus accusamus delectus incidunt. Nemo eos quis consectetur placeat tenetur. Odit nulla doloremque sed quis dolores eos. Repellat quisquam accusamus libero sunt earum earum. Doloribus maxime accusamus corrupti repellat ut id.</p>', 'https://via.placeholder.com/800x400.png/00ff44?text=nature+reiciendis', 0, 'est-vitae-labore-id-libero-ad-eligendi601ef1de703f1', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(4, 6, 8, 'Rerum quia in cum eum ad nihil repellendus ab.', '<p>Nulla sapiente aliquid quaerat ut ipsam. Ut voluptatem eos consectetur id sunt similique voluptatem perferendis. Voluptatem laboriosam ex dolores perferendis earum nemo. Maiores explicabo nihil excepturi corporis ducimus. Sint ut cumque ab sed. Quae ut reprehenderit qui veritatis accusamus. Nobis quis vel nisi. Dolor voluptatem blanditiis nobis molestiae quae recusandae eum. Suscipit deleniti molestias quia qui dicta. Est perferendis inventore aut. Aliquid fuga dolores velit in. Natus in deleniti minima nemo quos aut ut. Et quod quidem in adipisci accusantium aut. Animi nisi harum dolore rerum laboriosam. Quia possimus sunt ipsum aut dicta sunt. Consequuntur nam nisi voluptatem harum nobis sapiente possimus. Aspernatur vero autem qui et laudantium quas. Tenetur quis quam asperiores eos molestiae. Sed et fugiat eaque commodi libero. Laboriosam tempore saepe rerum necessitatibus sed. Quo in ut similique vel. Quia animi delectus itaque quia ab veritatis. Eveniet saepe sit libero vitae aut aut. Incidunt temporibus corporis quisquam. Alias doloremque sed sint ab. Laborum et aut reiciendis quo atque architecto accusamus. Accusantium quas consectetur similique amet ipsa a qui. Cumque et eius et qui vel molestias sit. Ipsum accusamus est magni. Doloremque dolor ut ducimus deserunt voluptatibus aut. Ut accusamus eaque ut corrupti ut. Et blanditiis non accusantium mollitia unde necessitatibus. Nobis voluptas cumque aliquam error voluptas est. Est nihil veritatis omnis facere voluptatem quis. Ipsam delectus nesciunt iste deleniti. Quia culpa dolorem minus exercitationem amet. Perspiciatis et animi repellat non. Reprehenderit earum rerum hic rerum. Possimus magnam reprehenderit deleniti magnam placeat laboriosam.</p>', 'https://via.placeholder.com/800x400.png/00dd66?text=nature+voluptatem', 0, 'rerum-quia-in-cum-eum-ad-nihil-repellendus-ab601ef1de71326', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(5, 2, 8, 'Consequatur at expedita nulla qui eos.', '<p>Natus suscipit sint a repellendus possimus voluptatem inventore. Architecto assumenda dolorum voluptatem sit voluptas minus quibusdam. Nobis minus commodi necessitatibus hic dignissimos. Sit libero nisi dolor inventore libero quisquam molestias. Est sed quibusdam omnis sunt. Velit omnis ut non fuga vel. Iste voluptatibus expedita maiores atque qui sed. Totam porro inventore voluptatem quidem quis. Aut totam eos laborum vitae veniam voluptatibus ea ratione. Blanditiis et qui nulla perferendis ea voluptates. Asperiores iste corrupti sed. Deleniti nulla error porro numquam distinctio minus maiores. Deserunt est et magni maxime nobis. Sit voluptatem tempora modi non. Accusantium quod non adipisci recusandae. Nobis explicabo eum occaecati dolorem quos nihil incidunt. Voluptatem dolorem qui omnis id nihil quam. Rerum praesentium aut nostrum similique necessitatibus. Quod illum sed autem autem cupiditate. Explicabo laudantium aut quia minima repellendus iure. Deleniti sint iste eos doloremque quia sequi recusandae. Quia quaerat laboriosam earum velit. Iusto corporis modi ut nostrum praesentium consequatur quis. Dolorem aut sunt officia qui similique hic quam placeat. Quaerat a optio minus non. Et a voluptas tempore quia qui. Facere vel molestiae labore. Maiores enim iste architecto provident voluptatem mollitia vitae quasi. Voluptatem iure nihil eos laboriosam. Sapiente et molestiae ut. Sit deleniti vitae temporibus modi sunt et pariatur. Ea sequi consequuntur praesentium sunt molestiae dolores. Iure est beatae quaerat aliquam. Consequatur quis ab iure veniam a aliquam doloremque officia. Debitis distinctio harum consectetur eligendi cupiditate. Corrupti et quis dolores nostrum.</p>', 'https://via.placeholder.com/800x400.png/00ccbb?text=nature+necessitatibus', 0, 'consequatur-at-expedita-nulla-qui-eos601ef1de71f02', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(6, 3, 1, 'Nam iure nihil velit error.', '<p>Cumque tempore laudantium sed laudantium libero ad accusamus. Delectus voluptas dolor aut et. Maxime et provident sunt. Dolores qui soluta et est sunt. Nemo cupiditate consequatur vitae fugiat odit quo assumenda possimus. Architecto dolor omnis magni consectetur molestiae. Natus eum voluptate ea consectetur. Qui illum quidem rerum aut eos. Adipisci error molestiae laboriosam id. Earum ad omnis quia qui hic nulla eaque. Sequi maiores facere vel ea repellat et quo eaque. Nulla vel possimus reiciendis. Sunt voluptatem et deserunt facere aut voluptas. Velit officia ratione et possimus impedit corporis. Magni incidunt velit et qui aut et. Amet recusandae omnis ut ipsum rem sunt. Voluptatem aspernatur ea molestiae sequi laudantium sit libero. Quia rerum quo rerum cum sit debitis. Perferendis sint reiciendis voluptatem tempora molestias repudiandae animi. Recusandae quas suscipit voluptatibus hic doloribus. Architecto et impedit et explicabo placeat itaque. Facilis aut ut et iste voluptates. Asperiores error dolore quia perspiciatis autem et laudantium. Ut atque quo omnis minus. Odio nihil provident dolores et rem officia. Dolorem dolorum amet quidem. Voluptas atque fugit ipsam doloribus veritatis numquam. Magni aut eius cumque odit occaecati. Omnis sit eos illum exercitationem error. Modi quod dolor dolore aliquid facilis explicabo. Molestias velit magni molestiae error quia animi est quibusdam. Nulla qui nam sequi optio rerum nobis dolore. Vitae reprehenderit culpa iusto placeat aut. Nisi cum aliquid ipsa laudantium. Magni ea aut incidunt eaque. Voluptatem ducimus dolorum quod fuga. Unde aut pariatur debitis consequatur doloribus dolorem est. Sed aliquam cumque enim. Facere consectetur labore quae totam excepturi saepe ratione. Ipsa excepturi omnis sed. Sunt fuga qui fugit. Non est rerum eveniet assumenda ea. Et eos corrupti nesciunt. Veritatis dignissimos cumque aperiam excepturi accusantium voluptatum velit. Dolor et autem aut rem. Necessitatibus expedita ut molestias dolores cum qui sint. Rem dolorem iure optio at enim eveniet necessitatibus. Enim in et et ratione enim.</p>', 'https://via.placeholder.com/800x400.png/005588?text=nature+quo', 0, 'nam-iure-nihil-velit-error601ef1de72b64', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(7, 6, 4, 'Rerum consectetur deserunt officiis iusto quo dolor.', '<p>Atque ut autem aut nemo et. Saepe quis fuga minus ad. Officia eius nemo ut dolores exercitationem libero ex. Sequi fugit qui laboriosam totam explicabo. Debitis porro quasi sed quia repellat. Quia illo culpa laboriosam quod error. Rerum ipsam labore ut aperiam placeat quam sunt sit. Voluptatum aperiam ullam et et. Tempore quo sapiente hic ut voluptatem. Veritatis distinctio eos sequi quibusdam voluptatem. Hic quaerat expedita quibusdam magnam quod ullam quos ut. Qui autem libero non harum distinctio similique. Soluta ducimus nesciunt quisquam vitae pariatur recusandae. Voluptas non inventore sed consectetur nemo. A repellendus animi in beatae. Eveniet quia qui in officia laboriosam. Veritatis aperiam ut quae velit. Dolore adipisci libero repudiandae occaecati. Suscipit ab corporis sunt et voluptates. Ullam quae rerum ut et aliquid impedit mollitia. Aliquid cumque et molestiae rem suscipit qui. Est quo dicta eveniet. Perferendis omnis sit assumenda et ipsum nobis sint. Eaque id officia quaerat molestiae. Alias aliquid est perferendis dolor. Pariatur veniam eum fugit possimus magni id rem. Laudantium aut expedita omnis corrupti ipsum expedita tenetur. Quisquam asperiores non sunt quia. Quos impedit delectus quia alias dolores incidunt eaque non. Animi officiis fugiat autem et. Itaque et aut eum vel sequi consequatur aut. Aut et praesentium assumenda vel repellendus a consectetur harum. Porro adipisci officia officiis animi praesentium magnam quia.</p>', 'https://via.placeholder.com/800x400.png/001177?text=nature+iure', 0, 'rerum-consectetur-deserunt-officiis-iusto-quo-dolor601ef1de73960', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(8, 5, 7, 'Pariatur vel ut eos et aperiam numquam voluptatem qui.', '<p>Beatae a voluptas doloremque. Non ut sed eum molestias voluptatem. Voluptas magnam rerum et et dolorem. Soluta eum sed quae placeat qui. Consectetur explicabo reprehenderit quaerat dolorum quibusdam. Quis odit dicta quod autem tenetur odio id. Sunt velit qui quod iste consequatur repudiandae laboriosam. Qui ex ex autem consequatur provident fugiat deserunt. Perferendis ipsa corrupti error quos eos ducimus omnis. Nulla qui autem ut iure quidem eius. Expedita esse vel et id. Dolores sequi corrupti libero in aut. Ea suscipit accusamus molestiae eligendi beatae fugiat. Porro eius facilis quis alias nobis. Nobis beatae qui aut laudantium est. Soluta delectus sunt dignissimos qui. Quo minus est aut. Similique eum repellendus commodi officiis quasi quas architecto. Dolor fugit sit ipsum eligendi dolor velit. Fugit libero voluptate voluptatem incidunt quisquam. Alias ipsa tempora in qui. Velit voluptatem ducimus ipsa natus possimus. Sit quo quia aliquam tenetur. Velit omnis nisi facilis perferendis illo fuga. Vitae aut consequuntur repellat culpa quisquam. Est quae ex distinctio ut. Non ratione in ut consequatur accusantium. Sit corrupti est eligendi consequatur et id. Voluptatem et recusandae est ut accusantium quo minus. Eveniet dolor voluptatem quia ut. Deleniti qui vel similique ut sed earum.</p>', 'https://via.placeholder.com/800x400.png/001122?text=nature+aut', 0, 'pariatur-vel-ut-eos-et-aperiam-numquam-voluptatem-qui601ef1de7450a', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(9, 1, 3, 'Numquam repellat provident sint consectetur eius amet.', '<p>Praesentium cupiditate aut odit exercitationem aut assumenda. Vel illo atque repellat. Eligendi nulla eveniet facere minima excepturi totam qui. Maxime hic voluptas est blanditiis quia consequatur ducimus nam. Consequuntur odit nostrum aliquid doloribus maiores sed incidunt. Iste nihil labore similique iste in debitis. Vitae ipsum quisquam ullam cum eos est nesciunt inventore. Sint ut voluptas sed qui dolorem minus facere. Fugit odit qui consectetur possimus voluptatem. Ducimus quisquam in vitae a. Dolorem soluta nostrum quaerat sit qui. Similique fuga sint tempora ipsum. Quaerat eum culpa aperiam. Neque in sapiente aspernatur sunt voluptates. Et error voluptatem voluptate impedit sed ab. Recusandae et velit reiciendis dolor minus. Sit consequuntur ut nobis nisi qui exercitationem sit. Soluta quas magnam odit tenetur molestias sunt. Sapiente et qui placeat consequatur assumenda. Praesentium voluptates dolorum sint similique voluptas id. Delectus illo modi sit voluptatem repudiandae qui. Accusantium odit inventore distinctio pariatur expedita. Distinctio voluptate voluptatum blanditiis exercitationem exercitationem voluptates et. Natus mollitia esse distinctio. Nihil quia assumenda atque. Officiis aspernatur et repudiandae amet voluptates ratione. Dolorem deleniti id tenetur officia praesentium dolorem qui ea. Est aut id impedit laudantium voluptatum dolor sit. Quo rerum asperiores sequi ex. Magnam inventore quae pariatur delectus illo esse. Fuga corrupti nulla sit velit nihil eos aliquid.</p>', 'https://via.placeholder.com/800x400.png/00ff33?text=nature+et', 0, 'numquam-repellat-provident-sint-consectetur-eius-amet601ef1de7528a', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(10, 7, 3, 'Doloribus inventore rerum exercitationem ullam eos nesciunt.', '<p>Voluptate placeat aut ratione molestias facilis dicta ut. Odit accusamus qui facere officia architecto cumque. Officiis quasi sint officia voluptas earum iure blanditiis. Quis laudantium amet sapiente quos suscipit maiores aut. Cumque consequatur ut quod laboriosam sapiente sequi. Ut enim debitis debitis eos. Consequuntur asperiores sint voluptates quasi consequatur. Saepe temporibus consectetur hic modi. Corporis ut et numquam dolor neque optio sunt. Ex qui non porro veniam. Ut accusamus sunt nam harum. Quod est ipsum voluptates qui at. Aut excepturi in omnis omnis iure. Eaque sit adipisci voluptatem. Quisquam praesentium corrupti libero minima porro id. Rerum modi necessitatibus asperiores quae voluptate enim. Non laboriosam ipsum sed quia aspernatur dolore qui. Molestiae minus modi provident. Est iure qui facilis in eius. Sit quaerat architecto non fugiat laboriosam beatae itaque at. Et accusamus omnis dolores quia sed nam beatae harum. Doloribus debitis laboriosam atque quo et ipsum. Reiciendis quas at in. Doloribus dicta sint nihil accusantium cum. Omnis quo fugiat voluptates explicabo facere voluptatem doloremque. Voluptas voluptas aut laboriosam unde tempore eius blanditiis. Non repellendus aspernatur totam quis. Corporis nemo dicta unde aliquid. Delectus necessitatibus asperiores enim qui. Qui officiis reprehenderit aut earum iusto. Qui debitis enim dolores. Et odio magni dolorem id ab qui doloremque. Ut cumque itaque sint beatae aperiam animi aut hic. Enim doloremque suscipit excepturi aliquam explicabo nesciunt. Explicabo pariatur dolor ut in debitis consequatur ex. Saepe non in nemo voluptas. Repellat consequuntur natus optio quam quo repudiandae.</p>', 'https://via.placeholder.com/800x400.png/00bbaa?text=nature+est', 0, 'doloribus-inventore-rerum-exercitationem-ullam-eos-nesciunt601ef1de76221', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(11, 5, 2, 'Autem reprehenderit ea recusandae earum.', '<p>At velit voluptatibus rem. Consequatur minus laudantium voluptatibus. Aliquam sit nulla et rem distinctio repellat vel iste. Laboriosam sit esse alias impedit. Porro expedita error et sint dolorem explicabo vero. Quaerat aut adipisci adipisci consequatur eaque. Consequuntur eos et est minus non est aperiam. Qui beatae praesentium et sequi nam. Culpa pariatur dolor autem adipisci ut non provident. Amet sit veritatis tempora aut unde. Laborum necessitatibus sapiente blanditiis quia. Doloremque commodi cumque qui. Doloremque sed sed porro repudiandae minima. At adipisci sed et officiis quia. Eos iste eligendi eius dolorem. Ad assumenda eius illum sit tenetur sint. Quidem est autem qui ipsam debitis numquam id temporibus. Tempora reiciendis sunt ex inventore. Ea ut ullam accusantium. Nobis consectetur et pariatur. Quis repellendus soluta et reprehenderit. Consequatur eum ipsum ea nesciunt delectus voluptas. Ad dicta sit quia nemo et numquam nihil. Molestiae ut inventore molestias officia optio. Labore voluptate eos optio alias aut. Architecto suscipit fugit et.</p>', 'https://via.placeholder.com/800x400.png/002288?text=nature+atque', 0, 'autem-reprehenderit-ea-recusandae-earum601ef1de76f69', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(12, 3, 9, 'Enim rerum iure cum soluta atque at.', '<p>Ut veniam laudantium et iste nesciunt quaerat. Deleniti natus et tempora aut. Consequatur placeat sunt nam id voluptas ullam. Est facilis possimus impedit nesciunt enim. Sunt voluptatem occaecati ut aut nesciunt illum perferendis. Velit dolor vero dolorem porro sed hic cum. Modi numquam dolores hic sequi dolores vel reprehenderit id. Accusamus quasi repudiandae molestiae et dolorem. Et possimus velit doloremque rem voluptas et. Tempora est quo nostrum labore. Dolores sunt et ut. Dolor consequatur ut nostrum odio a molestiae et. Voluptatem saepe pariatur quae. Voluptatem sed eos suscipit quasi enim sit. Et velit quia illo cupiditate debitis aspernatur. Accusamus est consequuntur modi et dolores. Perferendis qui id doloribus sit sapiente. Debitis omnis porro dolores aut quod tenetur eos. Id quibusdam quisquam provident eveniet sit sed. Et voluptatem asperiores aut mollitia vero blanditiis error. Eligendi omnis molestiae architecto. Et sunt molestiae neque possimus quia. Et quidem rerum iure accusantium voluptatem. Iste vero occaecati itaque delectus qui aliquid quasi. Rerum libero ea fuga debitis ut ut explicabo. Quia odio aut et architecto autem sint qui. Sint perferendis dolor voluptates. Amet sit iusto hic omnis architecto incidunt. Id facere et magni dolores aliquid magni tenetur.</p>', 'https://via.placeholder.com/800x400.png/00ee44?text=nature+vitae', 0, 'enim-rerum-iure-cum-soluta-atque-at601ef1de77c03', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(13, 2, 8, 'Corrupti esse aut nobis veniam.', '<p>Voluptate aperiam sit consequatur pariatur recusandae rerum. Tempore ea velit quasi est expedita at mollitia nulla. Est error possimus qui sit minus. Illo explicabo impedit voluptates tempora. Nisi quod quis doloremque quisquam corporis ut. Ipsa error repellat accusantium consequatur. Aut fugiat quae tempora cupiditate. Facilis id totam nemo. Et velit voluptatem ad repellat et nam. Illo unde adipisci consequatur magni consequuntur. Facilis qui possimus temporibus iure. Optio quia excepturi sint voluptates voluptatibus error sunt. Enim expedita laboriosam et praesentium. Architecto animi explicabo repellat assumenda quam. Maxime atque error dicta. Velit esse ea eos veritatis reprehenderit. Quia mollitia ipsam iure magnam. Quos fuga maxime quasi consequatur et perspiciatis voluptatum. Blanditiis earum provident dolore veniam voluptas esse ea dolores. Impedit repellat labore eum velit magnam ut sapiente. Sit et quam et aperiam similique enim. Earum omnis facilis in blanditiis laboriosam. Laboriosam commodi tempora quia vel rerum non. Impedit atque est ea qui alias voluptas harum. Officia quae quam tenetur sint quaerat ad. Natus beatae maiores recusandae voluptatum dignissimos sit explicabo. Sequi qui in reprehenderit nulla qui eum blanditiis. Omnis qui ipsa eum similique ut atque. Accusamus voluptate nobis non quo voluptates et. Similique nesciunt ut expedita laudantium quo modi sed. Voluptatum repellendus consectetur sit eius. Adipisci tempore eaque tempore dolore illum temporibus earum. Ut accusamus et pariatur occaecati quisquam a et. Aliquid saepe consectetur reprehenderit in suscipit aliquid eveniet. Eum voluptas deleniti eos sunt. Deleniti sint commodi quaerat. Sit voluptate alias rerum hic. Id est autem sunt sunt voluptatem ut. Atque ut voluptatibus vitae ratione nihil ab. Dolor et aut vel distinctio sed corporis illum et. Ut velit aut in nesciunt explicabo exercitationem sit. Ad et accusantium esse ex ullam non. Aliquam ab velit in occaecati dolorem officiis. Dolorem nobis sequi distinctio voluptate sit ipsum ab. Voluptates aspernatur illum veritatis mollitia est. Accusantium provident molestias id beatae iusto eos velit. Et tempora corporis totam et hic dolores tempore. Blanditiis totam temporibus velit cumque totam. Consectetur enim rerum ut quia eligendi. Ad a illo ut ducimus.</p>', 'https://via.placeholder.com/800x400.png/0088cc?text=nature+aliquam', 0, 'corrupti-esse-aut-nobis-veniam601ef1de78adb', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(14, 2, 4, 'Quae qui assumenda consequatur repellat nemo.', '<p>Culpa aut officiis temporibus. Mollitia suscipit quis ut qui. Omnis corrupti rerum mollitia voluptas vel. Praesentium facilis animi quia voluptatem necessitatibus nisi. Et rerum aut qui sint. Ea est provident deserunt vel veniam aliquam. Tempora eligendi dolore laborum nam quia voluptas nihil. Quia eaque dicta sit dolores maxime quidem velit. Sequi impedit voluptas aut asperiores sequi aut. Aut quasi autem earum placeat. Autem ad eligendi sed dolores sit ducimus. Neque molestiae sit et neque at nam facilis. Quo ratione esse pariatur voluptatem tempora. Molestias tenetur maxime hic itaque facilis sed. Consectetur laborum quia quia eligendi ipsa accusantium nisi animi. Atque distinctio sunt est quis sapiente repudiandae et. Impedit non aspernatur molestias tempora maxime quia omnis. Deserunt sed sed rerum aut. Quam quae laudantium quisquam ea. Ab commodi maiores architecto ratione sint. Et harum quia voluptatem. Consectetur dolorem in in aut nemo. Ea magnam provident sint doloribus et iusto fugit. Ut ut vitae rerum. Distinctio laborum cumque fugit voluptatem eaque ut. Similique ut aliquid aut velit. Veritatis illo totam reprehenderit optio ipsa rem vel. Laudantium similique assumenda temporibus ipsam assumenda in.</p>', 'https://via.placeholder.com/800x400.png/0011ee?text=nature+quidem', 0, 'quae-qui-assumenda-consequatur-repellat-nemo601ef1de79e20', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(15, 1, 2, 'Neque eveniet quia deserunt repellat et.', '<p>Ipsum perferendis repellat eum quia rem dicta dignissimos. Omnis quas non pariatur. Reprehenderit quasi itaque perferendis commodi dolore aspernatur. Sapiente pariatur impedit magnam. Laudantium eum vel et sint fugiat ab qui blanditiis. Ab et rem facilis nemo sit nisi ipsa eius. In odio dolorum tenetur magnam ratione dolor ad architecto. Praesentium qui sunt quia omnis illo officia. Quisquam et nemo perspiciatis ut libero veritatis. At officiis aut qui sint in doloribus molestiae illum. Consectetur est aut voluptas quia ullam officiis qui. Aperiam quaerat enim voluptatum culpa sed. Et et ut et sequi. Sit unde non libero nemo architecto. Omnis voluptates distinctio totam praesentium. Et omnis cupiditate hic. Earum laboriosam ea dolorem rerum et minima nihil sed. Sed ut provident debitis dolores aliquam quis. Molestiae consequatur tempore enim vel numquam rerum. Voluptatem enim quibusdam sunt nulla officia repudiandae. Beatae dignissimos nobis expedita adipisci est. Delectus id saepe autem a. Sequi ut est ad qui veritatis qui. Quas est est numquam sed dolorem qui. Totam perspiciatis cumque ratione quam porro et qui. Sed qui expedita blanditiis qui. Corrupti dolor ut aliquam laborum necessitatibus. Aperiam possimus quod quos saepe. Omnis impedit aspernatur ullam. Aut voluptas asperiores nihil sint. Expedita perspiciatis quis quis ex. Consequatur impedit rerum praesentium eveniet rerum dolorem. Aut ut laudantium placeat sit optio rerum omnis.</p>', 'https://via.placeholder.com/800x400.png/00bb22?text=nature+pariatur', 0, 'neque-eveniet-quia-deserunt-repellat-et601ef1de7ac13', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(16, 4, 8, 'Possimus nihil sit reiciendis veritatis dolor temporibus rerum qui autem qui.', '<p>Delectus voluptas qui ipsam. Reprehenderit quod iste qui velit et cumque et in. Dolorum dicta possimus sapiente impedit dolores et. Omnis aspernatur porro ab mollitia porro molestiae. Nemo et quia non sequi. Totam et omnis vel. Delectus deleniti ducimus eveniet. Voluptatem earum et ipsa vel. Ea consequatur commodi ab explicabo. Sed dolores aspernatur eos fugit repudiandae qui consequuntur. Similique voluptas doloremque aliquam omnis nostrum fugit. Perspiciatis dicta labore labore ipsum et ipsum. Sed occaecati totam ullam sed. Officiis vel quasi vitae consectetur ea. Mollitia repellendus magni voluptatibus error nisi reiciendis. Aperiam eum dolores porro voluptatem. Laboriosam labore laudantium omnis ut. Laudantium debitis quae itaque. Ullam et excepturi quibusdam excepturi laudantium. Soluta est eligendi ad sequi minima. Ratione sed non rem non. Dolores voluptatem odio error sit modi doloribus numquam. Officia alias sit ipsum distinctio. Cupiditate esse corrupti molestias deserunt necessitatibus atque minima. Numquam et excepturi cumque et eum qui. Et expedita voluptatem sint nobis rerum accusantium veniam. Veniam magni rerum commodi. Omnis iste repellat non ea ad quidem. Ratione vitae est asperiores atque ut. Debitis accusantium reprehenderit voluptatem officiis perspiciatis doloremque. Iure soluta nobis rerum facilis. Aut nihil vel sunt facere minima provident. Qui illum delectus et nihil perspiciatis. Quisquam et explicabo quidem provident ratione. In ab dignissimos repudiandae autem nam. Deserunt iure et est quia aut laudantium nostrum. Inventore qui hic quis et aliquam ea laudantium officia. Veritatis et qui ut ducimus ipsum consequuntur id. Blanditiis ipsam cupiditate repellendus. Blanditiis rerum quam doloribus quis porro atque veritatis. Excepturi reiciendis voluptatem dignissimos labore sunt consequuntur explicabo. Rem nisi amet nihil aut. Ut dolores maiores ut quae tenetur placeat. Facilis optio sequi et consequatur odit. Voluptas est aut rerum libero quasi tempore. Aut laudantium atque voluptas. Necessitatibus suscipit voluptatibus nam nostrum et rerum pariatur officiis. Eaque atque et odit. Temporibus accusantium iste aut in. Minima magnam porro quam aut commodi ut.</p>', 'https://via.placeholder.com/800x400.png/00ffee?text=nature+est', 0, 'possimus-nihil-sit-reiciendis-veritatis-dolor-temporibus-rerum-qui-autem-qui601ef1de7ba8a', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(17, 2, 4, 'Delectus occaecati facere sed.', '<p>Error et qui sint in et incidunt odio. Quia nulla ut et. Maiores sapiente corporis est quis. Qui quod sit laudantium qui tenetur molestias repellat. Numquam deleniti accusantium consequatur omnis nemo molestiae labore. Molestiae est explicabo minima vel dolor qui quo. Illum laudantium error in vitae enim voluptates. Eaque dolor consequatur omnis facilis voluptatem. Sed quibusdam quos consequatur ipsa et aliquid. Animi autem in voluptatem debitis et. Eveniet nisi est aut temporibus quisquam. Labore et repudiandae ipsum nisi dolores error. Repudiandae reiciendis voluptate libero ea deleniti. Vel quia nulla sint et quis sint. Quasi exercitationem sint repellendus commodi. Quis voluptatem nemo nostrum quasi cumque. Voluptatem odio alias culpa alias nihil ut. Sunt minima porro ipsum dolorem inventore. Ea eius eos id molestiae non. Fuga beatae veniam sit. Totam sed rerum rerum tenetur deserunt esse dolor. Et laborum quod eius et. Blanditiis error impedit tenetur veniam repudiandae. Rerum fugit omnis harum inventore id maiores eligendi cum. Vitae temporibus illum ut impedit commodi est voluptas. Ad ipsum autem vel facilis. Unde consequuntur quis atque aut omnis maxime est qui. Vero sunt non ut corrupti. Magni repudiandae sint porro voluptatem dolores. Ut quia eos itaque blanditiis consequatur veritatis. Officiis consequatur dolor id iste quas et. Expedita voluptatem quod sunt enim eligendi. Voluptatibus aperiam voluptas quos. Suscipit et nesciunt blanditiis similique alias. Voluptatem ut aut aperiam in. Modi dolores incidunt deleniti aut provident quia. Et distinctio autem et ea veniam beatae dolore. Ut nulla id ipsa dolorem consequatur. Voluptatem exercitationem nihil quis ut consequuntur mollitia dignissimos. Possimus inventore cumque quo deleniti ut dolorum et soluta. Beatae quia et quis ut. Impedit provident doloribus quo consectetur nulla. Sint nihil natus temporibus.</p>', 'https://via.placeholder.com/800x400.png/005588?text=nature+rerum', 0, 'delectus-occaecati-facere-sed601ef1de7c8ac', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(18, 1, 5, 'Iste deserunt ducimus et laboriosam aut.', '<p>Voluptatem sit similique sint exercitationem in totam esse. Quia aut velit laborum cupiditate. Eius culpa ea officiis recusandae quis. Minus ut occaecati iste illum debitis mollitia. Ad quam fuga veniam sed harum non. Repellendus esse veritatis aperiam. Voluptatem qui earum dolor molestias est molestias ut. Omnis quis voluptate culpa earum numquam sed quasi quisquam. Quam vero et enim placeat deleniti voluptas. Quo ratione sapiente ut provident architecto. Aut sapiente magni debitis tenetur. Fuga deleniti eum non aliquid. Consequatur libero quidem qui non qui. Omnis tenetur exercitationem repudiandae rerum eaque harum. Sit temporibus sit eum esse id sed qui similique. Ex nisi voluptatem neque quam ea dolore maxime. Ut asperiores omnis voluptate eaque nostrum numquam corporis sit. Ratione dolores dolore doloremque quam molestiae. Eos molestiae recusandae aut sed fuga omnis. Aut quia expedita praesentium sed. In voluptatem ipsum reprehenderit. Harum minima nulla velit ipsum inventore. Eveniet amet est doloremque similique voluptatum rem aliquid. Velit ex et illum nesciunt dolorum rerum. Reprehenderit exercitationem ab sint officiis magni vero. Quo rerum eum rerum et eos et quo. Amet vitae minima voluptas velit cupiditate. Quia vero dolores mollitia repellendus earum vitae iusto. Ad doloribus dolores voluptates. Aut dolorum nisi eum incidunt vitae non est ut. Sint ea asperiores animi officiis dignissimos consequuntur. Est sed nemo eos eum natus assumenda. Quaerat laboriosam aut ducimus vel. Temporibus neque ea velit dolor omnis voluptatem quas. Cupiditate tenetur laborum aspernatur nobis laudantium et mollitia. Ipsa omnis aliquid voluptatem beatae. Earum et suscipit porro provident architecto. Rem voluptate voluptate alias amet reprehenderit fugit sed.</p>', 'https://via.placeholder.com/800x400.png/0000bb?text=nature+ducimus', 0, 'iste-deserunt-ducimus-et-laboriosam-aut601ef1de7d726', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(19, 7, 8, 'Nesciunt inventore laborum ut et unde ad eum ullam.', '<p>Eius sit vel quidem nesciunt voluptas quis a. Qui quam et repudiandae minima vel distinctio vitae. Qui quo dicta doloribus magnam. Illo dolore minima animi nam neque ratione illo. Aut rerum ipsum dolores. Corporis at dicta cumque omnis voluptas qui. Architecto molestiae quam est ea. Et dignissimos eveniet maiores magni quos eos rem. Ea ut porro quia possimus praesentium soluta dolore. Voluptates dolore laboriosam facere temporibus natus mollitia minima. Suscipit labore qui quia maxime non. Qui fugit illum ratione autem eos eveniet. Adipisci rerum quod itaque animi occaecati eum. Ut laboriosam quasi nesciunt culpa non aut. Dolorum hic ipsum rerum architecto nulla iure in. Alias rerum exercitationem autem numquam odio odio voluptatem. Illum eos sit quam consequatur. Similique amet dolores vel corrupti quae. Eaque consequatur aut ex et sequi et dolores. Consequatur provident sapiente sequi qui sed sit. Ad accusamus molestiae architecto quibusdam in temporibus. Qui qui incidunt deleniti nulla. Maxime molestias sed dignissimos alias illo provident. Minima explicabo et in quia rerum harum. A eius optio commodi facilis aut facere minus. Consequatur animi doloribus saepe vero et facilis iste. Eaque expedita debitis maiores cupiditate dolorum quo omnis. Mollitia voluptas ut perspiciatis repellendus itaque tempora. Qui ut est minima repellendus. Molestiae placeat maxime possimus voluptas reiciendis iusto nemo enim. Et explicabo a quibusdam reiciendis soluta ut. Officiis consequatur ut et quasi assumenda explicabo eum. Qui unde blanditiis deleniti quas sit. Eum dolorem nam tempora est. Est officiis eaque temporibus. Qui rem qui voluptas voluptatem. Ut rerum omnis quis repudiandae id commodi placeat occaecati. Deserunt voluptas debitis nihil. Consequatur non ipsa enim consequuntur et. Voluptatem ut soluta placeat cum. Provident vero tenetur consequuntur dolore earum cupiditate. Enim dolore magni consectetur sed necessitatibus dicta. Molestiae quis aliquid perspiciatis pariatur. Sit omnis saepe voluptatibus. Nihil fuga ea consequuntur animi nesciunt. Veritatis dolor qui earum earum eum. Alias recusandae eos ea debitis officiis ipsa. Ab sint vel qui mollitia aut enim sunt optio.</p>', 'https://via.placeholder.com/800x400.png/002244?text=nature+earum', 0, 'nesciunt-inventore-laborum-ut-et-unde-ad-eum-ullam601ef1de7e640', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(20, 3, 3, 'Placeat et autem in optio.', '<p>Natus perspiciatis aut pariatur labore. Est repellat similique quaerat iusto voluptas. Autem voluptatibus similique voluptatum beatae dolorum. Perspiciatis possimus eum autem occaecati. Et omnis numquam eos quis quos excepturi nihil debitis. Qui et quisquam exercitationem deleniti recusandae. Laudantium deserunt quisquam quos cum. Tenetur enim unde vitae. Inventore sit adipisci sed voluptatibus. Voluptatem corporis nisi voluptas ipsam ut. Voluptatem consequatur odit illo quo id dicta. Ea est neque voluptates quia autem iure aut beatae. Modi quo sequi ex totam fugit minima. Aut nulla natus consequatur. Eligendi quaerat ipsam quidem voluptatem error ut. Deleniti ullam voluptas occaecati consequatur quo natus et expedita. Id delectus maxime doloremque exercitationem qui. Nostrum sed est est quia rerum ipsam error qui. Ea laborum a sint perferendis. Et consectetur molestias voluptas. Laudantium est facilis quia. Perferendis occaecati a debitis praesentium in. Aliquam est sint dolores natus et eos nisi. Velit et enim consectetur eaque voluptatibus possimus. Laboriosam excepturi repudiandae optio vero. Unde nihil delectus amet. Odit dolorem adipisci aperiam dolor saepe similique eveniet optio. Eius sint tempore itaque omnis. Sit quo minima nam commodi voluptas. Quis ut ipsum veniam tempora quod aliquam eveniet ullam. Accusantium consequatur optio pariatur accusamus aliquam repellendus eaque sed.</p>', 'https://via.placeholder.com/800x400.png/004499?text=nature+cum', 0, 'placeat-et-autem-in-optio601ef1de7f804', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(21, 6, 8, 'Qui suscipit itaque facilis maiores assumenda dolores dolor eaque.', '<p>Quod consequuntur vero possimus eius est omnis. Animi quae aut aspernatur voluptatum non nihil ab tempora. Blanditiis beatae a assumenda tenetur laborum eligendi dolorem rem. Deleniti et facere odio est distinctio voluptatem vel. Ipsum neque et animi ex rerum. A vel nisi consectetur saepe. Sit autem eaque qui temporibus temporibus minus. Rem placeat ducimus eum quae. Architecto consectetur sit et eligendi voluptate. A fugit voluptatibus sint ducimus. Recusandae nihil sequi architecto in numquam corporis nulla. Voluptatum nesciunt in ut voluptatem magnam autem. Quo deserunt qui voluptatem alias rerum. Et eos error ad iure omnis accusamus. Laudantium totam et est recusandae nulla optio explicabo. Eaque id aut et aut. Quis dolorem voluptatem quo vel quia. Ut facilis inventore ullam ipsum quia. Voluptas rerum enim praesentium ab alias a est. Quia hic distinctio sit ipsam qui. Minus accusamus quia voluptate quaerat aut. Eius consequuntur consequuntur asperiores. Voluptas quas beatae esse incidunt eum vel. Alias id expedita consequatur molestias. Eum ducimus tenetur vel qui quis facere. Natus perspiciatis sunt officiis ipsam porro nihil et.</p>', 'https://via.placeholder.com/800x400.png/0011ff?text=nature+et', 0, 'qui-suscipit-itaque-facilis-maiores-assumenda-dolores-dolor-eaque601ef1de81282', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(22, 4, 8, 'Hic ut quam vel amet aliquid alias odio rerum.', '<p>Fuga possimus non molestias. Non ut sunt animi repellat enim asperiores accusantium. Ullam quos nihil quia ducimus laudantium nulla ea. Quos facilis reprehenderit et nulla sit quia. Nesciunt possimus eligendi odit non amet est aspernatur ducimus. Quos voluptatem repellendus sapiente quod aut a. Enim suscipit provident expedita magnam. Occaecati velit modi sit dolorem rerum fugiat. Est debitis et incidunt placeat iste tempore voluptas. Veniam temporibus saepe natus et ea odio perspiciatis. Voluptatem nisi occaecati facere minus tenetur in. Rerum architecto vero itaque amet consequuntur magnam ipsam explicabo. Corporis tempora error quae nemo autem vel. Illum id facilis cum ipsa odit. Et vero aperiam nihil totam dolor quasi error. Alias aliquid sunt consequatur voluptas voluptas. Et aut fuga in quia quisquam saepe. Doloribus accusamus repudiandae magnam itaque impedit eum et vero. Numquam ducimus sint aliquam. Voluptatem et doloribus eum quia omnis. Quod fugit vel enim hic a quaerat sit ex. Temporibus et nisi et numquam dolore ea. Ullam aut omnis iste ea laborum ut similique possimus. Consequatur repellendus fugiat sapiente et voluptates incidunt possimus. Eum quo debitis nostrum officiis hic quos. Itaque officiis repellendus sunt et illo aut. Veritatis nulla rerum nemo magni. Recusandae ut similique voluptatibus laboriosam ea. Provident cupiditate consequuntur nisi dolorem cupiditate quis odio. Rerum sunt soluta aliquam. Nobis eum autem omnis. Omnis quas quia enim iure deleniti.</p>', 'https://via.placeholder.com/800x400.png/0077bb?text=nature+officiis', 0, 'hic-ut-quam-vel-amet-aliquid-alias-odio-rerum601ef1de82446', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(23, 4, 5, 'Placeat nisi a est ullam quam.', '<p>Officiis dolorem ullam quas voluptas fugiat praesentium. Aliquam quis provident cupiditate debitis dolores cum sed. Sit est occaecati laboriosam. Deserunt commodi magni eveniet ipsum. Non dolorem ut qui adipisci ea sunt exercitationem. Amet excepturi eius corrupti. Quis consequatur aut rerum pariatur. Veritatis voluptatem consectetur ipsam sunt. Mollitia aut est itaque atque rerum. Nobis maxime tenetur autem aliquam. Corporis beatae ipsum modi magni vel. Perferendis doloribus molestias dolor ipsum inventore eveniet possimus aliquam. Magni officiis rerum occaecati quidem earum ea voluptas. Voluptas itaque tempore officia ut. Rerum exercitationem culpa suscipit quia. Enim impedit pariatur sit optio et. Laudantium illo qui quod rerum officia mollitia. Distinctio est quia mollitia voluptas. Aliquid debitis non quibusdam consequuntur impedit sint. Itaque est deleniti beatae quod laborum. Rerum sequi aut quaerat quasi aut omnis. Officia culpa iure consequatur qui odit magni at. Architecto illum impedit quae similique sunt. Amet et voluptas earum voluptas quia explicabo. Error dignissimos in cumque et. Consequuntur nobis harum facere. Quia modi cum officia iure quis eos. In sint voluptates quis quia maxime. Maxime facere cupiditate quae ut. Ea quod eveniet porro alias magnam qui iure. Vel ducimus quis et dolorem. Dolorem mollitia id magni dignissimos. Dolorem earum enim quia hic. Eaque illo a reprehenderit omnis. Quaerat qui doloribus dolores repellat expedita quia. Ea occaecati deleniti est nihil est aut iusto.</p>', 'https://via.placeholder.com/800x400.png/000044?text=nature+sint', 0, 'placeat-nisi-a-est-ullam-quam601ef1de835ce', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(24, 1, 9, 'Ut libero recusandae earum dolore aliquid.', '<p>Et expedita vel officiis vel suscipit. Ut et commodi ad cupiditate velit. Esse qui eum eos eos id necessitatibus magni aut. Nam sed numquam et praesentium laudantium repellat. Praesentium dolor quas qui. Est voluptas adipisci eos dolores. Qui ut placeat doloremque ipsa. Commodi sequi perspiciatis est inventore omnis quibusdam soluta. Odit ipsum quia pariatur itaque et fugiat. Molestiae voluptas facere rem sit eos aliquam optio. Laborum eum velit cumque deserunt natus aut aliquid aperiam. Eius earum officiis itaque possimus doloremque. Soluta quibusdam at maxime praesentium architecto dolorum vel. Iusto et autem illum. Incidunt doloribus temporibus quidem dicta omnis cupiditate veritatis placeat. Molestiae cupiditate minus consequatur voluptas esse. Aspernatur veniam ut voluptate aut. Fugit illum est mollitia voluptatem. Explicabo quia dolores et voluptatem ut dolorem maxime in. Asperiores accusamus sint dolore sit harum omnis. Nam et possimus impedit. Incidunt aliquid quas veritatis quia. Est vel qui fuga et. Et aut ut odit. Sunt consectetur molestias quae adipisci sequi aut. Non occaecati neque excepturi debitis sit perspiciatis temporibus. Nostrum autem dolores voluptas unde. Distinctio nam ex ipsa non minus. Quia dolorum aut non sit sed. Labore et aut dolorem maxime quae. Rerum quo vel molestiae voluptatum consectetur sit. Enim illo est quia culpa qui ab aut. Pariatur velit atque ullam. Aspernatur illum dolores sit officia dolores nobis eius. Et rem veniam velit dolores ut asperiores nam. Praesentium deleniti nihil consequatur aliquam et accusamus laborum repellendus. Delectus voluptatibus qui nam a et repellat aperiam dolor. Porro necessitatibus architecto nobis itaque. Nihil at adipisci dolorum libero nihil aliquid totam.</p>', 'https://via.placeholder.com/800x400.png/0099cc?text=nature+est', 0, 'ut-libero-recusandae-earum-dolore-aliquid601ef1de8477b', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(25, 3, 1, 'Necessitatibus facere alias quasi.', '<p>Neque laborum necessitatibus qui facere deleniti. Suscipit iste voluptatem inventore est laboriosam veniam aut et. Ex id quis et eum esse molestiae. Sunt consequuntur autem minus esse. Tempore quidem fugiat delectus maiores. Ipsum est minima eveniet praesentium. Voluptatem saepe pariatur ex eos non incidunt. Dolores aut ea quae. Sapiente occaecati soluta odio temporibus quae totam cum. Et aut ipsum sed repudiandae laudantium voluptatem. Aut deserunt sed quo et. Dolor debitis magnam iure. Voluptas expedita sit maiores et fuga. Facere quo dolorem accusantium distinctio aut qui quia. Voluptatem enim sapiente exercitationem. Velit ut fugiat numquam eaque commodi voluptatum vel. Quidem alias sunt vel rerum id dolore. Ea sit est nisi non laudantium quasi et. Ut ut amet ut nostrum et ut. Est modi minima earum nihil. Nihil dolores et architecto veritatis a nulla. Voluptatem quia aut dicta optio ea quo et. Nulla iste illum suscipit optio assumenda est. Aut veniam sunt distinctio architecto mollitia. Natus neque ea assumenda et voluptas suscipit. Et numquam culpa quod ullam rerum earum. Animi aut praesentium est provident dolor. Odit rem consequatur dolore recusandae omnis mollitia. Provident est corrupti dicta id dolorum. Sit veniam occaecati recusandae error. Ab similique odit tempore ea placeat laudantium. Eveniet veniam voluptatem sunt magnam et. Id qui voluptates hic tenetur aperiam. Voluptatum quos asperiores sunt illum consequatur facere.</p>', 'https://via.placeholder.com/800x400.png/007799?text=nature+nam', 0, 'necessitatibus-facere-alias-quasi601ef1de858ce', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(26, 4, 2, 'Dolores qui illo eos et quisquam dicta vero.', '<p>Sequi nihil omnis sequi qui sapiente. Reiciendis quis soluta qui ducimus non. Exercitationem dolorem similique officia et et inventore vero. Totam quidem quos fuga. Quia error quos ut ut voluptate quis distinctio. Optio rem expedita iure error porro et sed. Sed sit excepturi et ratione inventore ut sed. Illum culpa natus animi ipsa recusandae error. Atque debitis laborum cumque suscipit ea sit. Doloribus assumenda ut voluptatem nam quo velit. Dolores et quis eos. Commodi nobis veritatis perferendis magnam corporis voluptatem quas. Ipsam recusandae pariatur et repellendus occaecati. Aut dignissimos natus quasi quaerat velit autem adipisci. Sed totam qui deserunt doloremque corrupti incidunt cum. Ea exercitationem sit quae rerum rem sit. Ut consequatur esse minima magni consequatur. Ullam velit est provident temporibus fuga quas. Et dolores et repellendus eligendi earum beatae incidunt quos. Recusandae est voluptas suscipit harum qui sed. Magnam earum aperiam quam fugiat. Ullam deleniti quis possimus distinctio sit rerum quidem nam. Rem nihil dolor et possimus. Inventore vel sapiente dolorum temporibus. Facilis cum harum et commodi qui. Dicta officiis et ex dicta velit voluptatem. Ipsa ab sed aut impedit et sapiente aut. Soluta tenetur rerum sed quod totam. Velit necessitatibus aut eum porro aut repudiandae culpa. Minima possimus culpa numquam nemo omnis eius accusantium. Vitae corrupti in optio consequatur. Illo quia occaecati consequatur expedita sequi fuga voluptatem. Ipsum ducimus qui laborum illo doloremque laboriosam sapiente explicabo. Nulla in velit et et velit aut. Expedita quia similique ad voluptatem velit deleniti dolorum. Explicabo recusandae et blanditiis distinctio asperiores omnis et. Quibusdam est velit sunt officiis eos. Et quidem est porro rem. Quidem dolores dolore cum veritatis. Animi consectetur sed consequatur et. Sapiente dignissimos non sed harum doloribus necessitatibus possimus. Tempora quaerat sed cupiditate eos voluptatum velit voluptates. Consectetur accusantium similique quae veniam rem eos. Saepe quas quod at fugit. Quasi laboriosam veniam praesentium sed ex eligendi. Eligendi et maxime ut omnis assumenda fugiat et.</p>', 'https://via.placeholder.com/800x400.png/009944?text=nature+quia', 0, 'dolores-qui-illo-eos-et-quisquam-dicta-vero601ef1de86ac8', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(27, 1, 3, 'Nam velit sed illo voluptatum est enim.', '<p>Ipsa et aut consequatur et. Ratione ex velit dignissimos aliquam ad non. Beatae accusantium ut nihil deserunt voluptates. Minus dolorum vero aspernatur animi est. Consectetur eos non omnis aut hic. At nostrum quas vero earum. Cumque nihil autem cupiditate natus voluptas. Officiis vel quod libero architecto. Aut eos necessitatibus inventore eius placeat quae corporis. Ea accusamus repudiandae repellat veniam sapiente eius. Qui eos eius cupiditate molestiae enim. Nemo commodi aut qui et impedit porro. Soluta consectetur necessitatibus voluptatem in a qui nobis labore. A sit consequatur ratione aliquam ullam ea. Quod animi et maxime quo magnam cupiditate. Et dignissimos dolor laborum repellendus. Mollitia delectus praesentium sit rerum sapiente consequatur. Est architecto debitis est laudantium quia. Quia aut omnis assumenda quod. Quidem minus numquam minima voluptatem ullam ullam. Qui est est iure voluptates sed qui. Mollitia pariatur cupiditate temporibus architecto vitae qui officia. Facilis illum officia distinctio sequi. Rerum voluptas amet ratione voluptatem harum. Ipsum autem unde in dolorum quae vel. Omnis suscipit accusantium tempora quam voluptas sequi a.</p>', 'https://via.placeholder.com/800x400.png/00ddaa?text=nature+optio', 0, 'nam-velit-sed-illo-voluptatum-est-enim601ef1de87be9', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(28, 2, 1, 'Veniam animi asperiores inventore rem sit est.', '<p>Et rerum ab animi possimus provident. Dolorem exercitationem hic totam minus vero officiis tempore. Eos voluptatem molestiae minus cum voluptatem est. Deleniti labore temporibus quis deleniti. Sint asperiores sed recusandae quidem officiis quisquam porro. Expedita temporibus qui autem et voluptas sunt minima. Nam ipsum quidem blanditiis voluptatem quaerat quia aperiam. Nemo suscipit voluptatem ratione odit libero. Suscipit similique sapiente suscipit possimus quo ratione ex. Nam molestias itaque fuga quos. Facere alias tenetur optio aut nam expedita. Ullam temporibus et sit sed eaque iusto. Sed necessitatibus molestiae autem doloremque rem voluptas. Eius aut eius aliquid quo dolores cupiditate. Mollitia molestiae ad enim repudiandae. Facilis quam fuga fuga blanditiis suscipit a. Illum culpa sit voluptatibus repellendus corporis a. Ipsa rerum nisi quod culpa. Rerum quia iste est ut. Quia in ea sunt distinctio ducimus repellendus laudantium. Tenetur accusantium sit officiis qui ab. Aut qui error et culpa. Blanditiis et officiis quod rerum at necessitatibus unde aperiam. Repudiandae ipsum ipsam sed tenetur asperiores. Rerum porro qui nemo nihil. Quia id ipsam minima dignissimos inventore libero. Doloremque soluta quaerat voluptatem eius omnis vero. Alias voluptas ex beatae id aut. Et facilis modi qui cupiditate placeat. Eum deserunt sit aut necessitatibus. Neque molestiae pariatur nobis maiores est. Molestiae cumque modi repellendus nulla voluptatem asperiores aperiam. Dolore et sunt nihil incidunt. Ipsa autem quia consequuntur quod qui. Facilis harum tenetur nemo molestiae officiis enim in dicta. Hic sed exercitationem fugit quidem vel.</p>', 'https://via.placeholder.com/800x400.png/006677?text=nature+et', 0, 'veniam-animi-asperiores-inventore-rem-sit-est601ef1de88d81', '2021-02-06 19:45:34', '2021-02-06 19:45:34');
INSERT INTO `articles` (`id`, `user_id`, `category_id`, `title`, `article`, `img`, `hit`, `slug`, `created_at`, `updated_at`) VALUES
(29, 7, 5, 'Nihil voluptatem sint quibusdam facilis voluptatem.', '<p>Temporibus et qui deleniti aspernatur animi dolorum. Voluptatibus laborum omnis illum autem quia. Non ipsum ratione numquam quaerat ab. Quisquam aut expedita eligendi libero voluptas ratione. Quas quo vitae dignissimos eligendi sed dolore sit qui. Quod repudiandae cupiditate alias laborum. Est ipsam totam molestiae nulla eveniet qui vero. Inventore nihil inventore quo quod. Rerum quidem distinctio facere quae voluptatem quia. Similique magnam explicabo earum quod voluptatibus ut accusantium. Maiores reiciendis quo at odit. Aperiam iste sit quis cumque aut. Dolores culpa sint ut rerum. Ut dolore laboriosam quibusdam exercitationem quidem. Enim asperiores dignissimos autem molestias sit. Sit rerum temporibus qui et. A laudantium culpa ab consequuntur pariatur ratione. Expedita consequatur qui quasi est quia odio impedit. Voluptatem expedita qui et in provident explicabo voluptatem amet. Sequi tempora assumenda et et. Reiciendis nostrum velit illum. Eos sint quidem ad consequatur molestiae eligendi. Est non quidem officiis dignissimos. Quo aut expedita provident accusamus recusandae quisquam. Impedit tenetur est fuga autem. Nam qui reprehenderit ut non. Alias et cumque maiores ut repudiandae. Est et quidem cupiditate ad iste autem. Dolorem error quae voluptatem cupiditate illo amet. Fugiat perferendis dolores aut enim asperiores ea. Fuga voluptas in blanditiis pariatur porro facere blanditiis. Sit et libero atque sit autem dolores. Laborum laboriosam iste et. Voluptatem commodi itaque dolorum praesentium. Voluptas sit id impedit vero repudiandae doloribus iure. Cum ut magni aliquid beatae. Rerum saepe neque asperiores nostrum debitis. Aut nihil et maxime vero. Autem ducimus magnam perferendis deleniti totam tenetur. Qui doloremque at et explicabo facilis. Totam consequuntur blanditiis saepe minima praesentium quia sed. Nobis reprehenderit ex alias id in iure impedit quisquam. Commodi expedita harum quia earum sed.</p>', 'https://via.placeholder.com/800x400.png/000044?text=nature+laborum', 0, 'nihil-voluptatem-sint-quibusdam-facilis-voluptatem601ef1de8a905', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(30, 4, 7, 'Atque magni laudantium possimus rerum est.', '<p>Consectetur esse nostrum et minus. Est et architecto temporibus exercitationem et ut. Animi sed aut qui eaque fugit aut culpa. Omnis rerum consequatur et facere omnis explicabo. Fugit doloribus nisi repellendus vitae beatae molestiae est. Molestias dignissimos qui ea doloremque rerum ipsa qui. Tenetur sit aut dolores. Optio nobis temporibus debitis vero fugit sit eligendi. Et molestiae illo corporis. Quod quia dicta quidem. Dolor rerum aut non. Ut natus et ex aut omnis distinctio. Similique aut repellendus blanditiis soluta. Est harum aspernatur voluptatem. Quae consequatur minus qui. Ut commodi numquam quos aut consequatur rerum. Ducimus architecto ipsam cumque expedita. Nobis pariatur quia repellat exercitationem dignissimos. Quisquam quaerat deserunt officia similique consequatur aspernatur ipsam magnam. Illo voluptatem delectus non occaecati dolor facilis. Ab saepe quasi quo eos et id. Voluptas consectetur voluptas voluptatem sit molestiae voluptas. Alias aut laborum autem aut eius hic sit. Quia pariatur et voluptates eum. Ut voluptates et fugiat dicta dolores. Suscipit id id quos quidem id. Dolore voluptatem et ea praesentium ipsum facilis eaque. Aut facere nulla perferendis dicta vitae ut. Similique veniam quod aut quod. Est eum tenetur consectetur et. Et quis iste ea vero quisquam sed qui. Ipsam excepturi qui possimus in. Dolores maiores nihil et eum veniam. Perferendis sit accusantium quas. Quia sint provident tempore id aperiam porro aut. Optio facilis eum doloribus eius cupiditate ipsa voluptate. Recusandae iure nobis consequatur provident. Minima et exercitationem et laudantium sit voluptate.</p>', 'https://via.placeholder.com/800x400.png/003333?text=nature+similique', 0, 'atque-magni-laudantium-possimus-rerum-est601ef1de8ba78', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(31, 2, 9, 'Qui omnis odit non ut.', '<p>Possimus quaerat dicta fugiat rem. Illo sit et accusantium non quisquam consequatur. Et nisi dolore qui aliquam. Neque omnis perspiciatis natus debitis harum nihil possimus minus. Qui consequuntur in voluptatem consequatur. Iure voluptas vitae velit eaque perspiciatis qui ullam. Culpa atque dignissimos fugiat accusantium et. Quidem rerum commodi eius cupiditate officia sit rem omnis. Omnis excepturi est commodi sequi sed qui. Necessitatibus necessitatibus eius harum consequatur veniam inventore eum. Est recusandae sunt ut repudiandae animi. Vel quis id et ipsam. Rerum molestias corporis omnis autem vel sit aut vel. Quia nihil ut quia. Est minima veniam necessitatibus quasi. Aut libero illo accusamus excepturi quia blanditiis et et. Error saepe quaerat nostrum sint quo. Ut incidunt voluptates consequatur odit iusto et minima iusto. Est in ipsa dolorum fugit. Incidunt expedita hic eius sunt voluptas omnis. Ea explicabo fugit itaque. Voluptas qui enim est sunt nisi. Id quam rerum unde et tempora sit voluptatem deleniti. Eveniet aliquid sunt voluptatem sed molestiae amet. Non est at similique sit eligendi doloremque. Tenetur ab est est est qui. Commodi et ullam dolores occaecati. Qui qui quas voluptate vero unde est. Cum id laborum nihil quo et sed. Tempore voluptas quis accusamus laudantium rerum. Ipsum quibusdam facere optio at qui tenetur et odio. Delectus inventore consequatur iure doloremque. Doloremque nostrum necessitatibus illum quidem. Vel repudiandae inventore magnam incidunt. Quas ex quidem cum rerum et. Quisquam enim voluptas cumque voluptatem. Distinctio sunt esse ut culpa. Sit qui voluptatibus necessitatibus ut ipsa amet. Saepe quae omnis maxime quia dignissimos. Blanditiis fugit perferendis qui quo laudantium voluptatem ea maiores. Optio unde natus necessitatibus facilis. Quasi ipsum et consectetur enim placeat. Officiis et vero asperiores est. Libero quia tempore doloremque quos a voluptatum. Sit possimus dolorum perspiciatis quae id ut. Ex temporibus possimus placeat delectus numquam aliquam animi est. Aut sed ad culpa optio laboriosam cumque. Rem temporibus voluptas rem qui quia dolorem excepturi ut.</p>', 'https://via.placeholder.com/800x400.png/00cc66?text=nature+dolore', 0, 'qui-omnis-odit-non-ut601ef1de8cd12', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(32, 4, 6, 'Eum recusandae numquam saepe officiis ex.', '<p>Nam saepe repudiandae aliquam a est itaque doloremque. Voluptas accusamus eaque reiciendis accusantium laboriosam quia minus ab. Iure commodi et in id et ut. Et assumenda dolor fugit reprehenderit saepe. Illo dolore ut sunt tempore possimus accusamus accusantium. Blanditiis consequuntur saepe iste vitae cumque nam. Voluptatem aut id commodi soluta. Et reiciendis praesentium ullam. Corrupti nam reiciendis enim et. Occaecati corrupti nulla quas itaque. Laborum hic possimus qui tempore consequatur. Aut ad non sapiente et ut praesentium. Rem voluptates ut in facilis dolores. Rerum eligendi minima nulla dicta est nesciunt rerum corporis. Quia praesentium et enim dolores ut a. Architecto est fuga illum cumque hic sequi. Possimus et voluptatem nostrum cum aut amet dicta. Ipsa maiores nam blanditiis dolores placeat aspernatur. Repellat velit veniam iure delectus dolorum. Quidem quae dolore ipsum quo totam rerum error. Blanditiis est enim doloremque delectus sed aut. Labore et adipisci facilis numquam possimus laboriosam. Alias aut debitis quasi porro recusandae non. Excepturi atque quod corporis incidunt sequi reiciendis. Nobis dolores praesentium necessitatibus quaerat. Nesciunt debitis expedita impedit nam rerum vitae quia voluptate. Aut autem totam aut assumenda ratione omnis fugit. Dolore eos consequuntur et et. Placeat qui vero et perspiciatis quaerat soluta. Sunt non quo illo reiciendis sunt cumque unde. Corporis enim ad voluptates consequuntur rerum aut aut. Consequatur voluptates accusantium tempora esse esse doloremque et atque. Consequatur deserunt quae rerum deleniti doloribus. Aut iste dolorem harum. Officia alias impedit voluptates enim illo maiores. Qui et sed reiciendis velit cupiditate eaque rem. Et aperiam in et repellendus error distinctio. Reiciendis perspiciatis vel voluptatibus assumenda voluptatum corrupti explicabo. Adipisci reprehenderit quia ut cumque iusto excepturi earum. Eum excepturi est qui asperiores. Esse et doloremque omnis commodi rerum ipsam dolores. Quam tempora et repellat eos magni quaerat maiores. Minus placeat quos ab quibusdam.</p>', 'https://via.placeholder.com/800x400.png/003322?text=nature+dignissimos', 0, 'eum-recusandae-numquam-saepe-officiis-ex601ef1de8e023', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(33, 4, 1, 'Et quod odio id voluptatem dolores non.', '<p>Cum aut dolorem et veniam nostrum recusandae. Doloremque est alias nesciunt quam voluptatem sit. Sapiente a maxime consequatur inventore officiis. In qui autem nemo et sit ullam voluptate. Blanditiis enim iusto aut sint. Repudiandae quia distinctio dolore dolor dolore iste doloremque. Porro hic rerum aut voluptatibus velit aliquam delectus dolor. Vero beatae illo ipsam. Eius non sint labore omnis odio porro. Consequatur rerum in facilis dolorem quibusdam voluptate est. Velit cumque mollitia reprehenderit eius ipsam pariatur quos. Qui dolores et veritatis molestias et vel sint. Quibusdam sapiente ea error quo enim voluptatem. Nam ipsum minima iusto rem facere atque. Optio laboriosam quam optio et perspiciatis. Perspiciatis ex ut deleniti eos labore. Repellendus ut qui est eveniet. Quam debitis magnam qui sit tempora quis perferendis. Vitae ut eligendi illum veniam quo. Possimus recusandae perspiciatis aut rerum repudiandae quo. Quo qui non modi velit nisi eveniet rerum. Sequi autem ducimus ea hic quis. Eligendi nulla nulla sapiente ipsum quas labore enim assumenda. Excepturi aut ipsam quis sit rerum sequi consequatur. Et et sequi at fugit modi. Libero amet a vel ex consequatur sint. Distinctio voluptatem autem incidunt sit alias vel. Laudantium quia non ab aut. Minus quos neque quae qui in. Neque sint mollitia quaerat voluptatem sed quod. Enim rerum nostrum itaque laboriosam minima. Quaerat et id sit perspiciatis soluta. Facilis enim qui quia aspernatur molestiae. Libero labore praesentium ratione et. Et et deserunt et et est. Quia omnis maiores consequuntur voluptatibus non distinctio. Doloremque sequi similique totam voluptatem. Aspernatur eos ipsa dicta nisi. Tempora nam cumque ut dolorem odio nemo sapiente quae. Est nisi mollitia saepe. Aut nobis hic quo numquam repudiandae. Qui consectetur omnis deserunt praesentium architecto voluptas id. Impedit rerum laborum omnis expedita facere aut voluptate adipisci. Cumque atque enim deleniti. Iure ut voluptates ex.</p>', 'https://via.placeholder.com/800x400.png/00eedd?text=nature+dolor', 0, 'et-quod-odio-id-voluptatem-dolores-non601ef1de8f261', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(34, 7, 1, 'Voluptatem sed perferendis porro quam doloremque.', '<p>Rerum voluptas eos blanditiis impedit. Culpa voluptas fugiat numquam sed. Molestiae molestiae et vel eum. Enim ad error debitis sapiente consequuntur aperiam. Molestiae explicabo ab et quia. Eaque aut repellendus et eos debitis et corrupti incidunt. Aut laborum et iste quod assumenda dicta. Minima voluptas voluptatem et ab. Voluptate sit consequatur vitae quam. Aliquam non debitis debitis et aut. Commodi eius ex molestiae itaque. Voluptates nobis voluptas facilis hic ipsa tenetur voluptatem animi. Quia sint et aut explicabo. Sunt rerum sunt repellat minus fugiat expedita consequatur. Odit itaque aut magni nisi inventore. Quidem qui et repellat laboriosam. Architecto et reprehenderit ducimus repellat sit debitis. Earum et aperiam quod et laboriosam illum praesentium. Atque occaecati est vel et natus ut. Et consequatur placeat non quibusdam quod. Delectus doloribus id eos. Accusamus quis quia sequi voluptatem. Distinctio qui quidem qui sit. Quis et ut totam minus. Et perferendis ex placeat aut in praesentium. Voluptatem optio doloribus aut rerum excepturi voluptatem dolorem. Mollitia nostrum quidem aspernatur nisi ea error repudiandae. Laborum accusamus perferendis animi repellendus. Aut enim dolorem enim eos fuga itaque quo quia. Eos in ratione numquam vel cupiditate iusto dolorem. At perspiciatis adipisci explicabo sunt. Odio cumque fuga illo quaerat aut soluta sunt. Aut consequuntur recusandae et nihil quidem eos. Eligendi enim fuga repellendus aut quod voluptatem aut maiores.</p>', 'https://via.placeholder.com/800x400.png/0022ee?text=nature+nam', 0, 'voluptatem-sed-perferendis-porro-quam-doloremque601ef1de904e4', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(35, 5, 9, 'Nemo dolor facere et.', '<p>Adipisci voluptas dolor molestiae reprehenderit et. Error non amet eveniet possimus corrupti rerum voluptatem non. Repudiandae aut consequuntur voluptatum totam aperiam maxime omnis maxime. Cumque mollitia at necessitatibus quas. Id error et harum porro eligendi. Repellat dolorem in recusandae ipsum dolore aut esse reiciendis. Velit placeat autem itaque qui. Doloremque omnis id porro hic ut tenetur omnis illo. Magni quam tenetur possimus. Dolor et aut nisi accusamus. Exercitationem molestias quibusdam in veniam velit est aliquid. Occaecati dignissimos nulla alias sint aut quia expedita delectus. Sint explicabo asperiores aut sint amet quis eius. Ut suscipit illum voluptatum velit. Quam corporis omnis expedita recusandae porro doloribus ut. Asperiores dolorum quo eaque consequuntur ab sunt. Et debitis quasi eveniet veniam optio non. Autem voluptas ratione consequatur. Ut molestiae et enim. Voluptatum voluptate deserunt ea similique doloremque recusandae. Laborum quam rerum iste. Saepe quae illo dolor minus. Labore odit omnis reprehenderit culpa. Labore est rerum nulla. Quam molestias illo dolorem quo ut. Qui minima aut eaque est in corrupti quam. Nihil veniam porro nostrum rerum. Omnis et possimus magni nemo sed molestiae. Iusto labore exercitationem et. Et corrupti non ut repudiandae. Quia nobis quae omnis qui rerum autem. Necessitatibus non officia nisi nesciunt esse voluptas. Deserunt nisi sit consectetur atque aut magnam. Voluptate totam nisi temporibus in. Consectetur fugit aut natus tempore tempore vel deserunt. Et pariatur vitae voluptatem eius quidem voluptatibus. Eum totam rem voluptatem dignissimos modi consequuntur quasi. Officia quia ipsum perferendis molestiae provident vitae. Pariatur et architecto aut velit consequatur. Distinctio quidem mollitia unde aliquid error ipsa. Sequi quas qui voluptatem omnis. Perferendis ut possimus maxime nemo omnis ratione voluptatem. Animi fugiat amet et veritatis aut blanditiis error.</p>', 'https://via.placeholder.com/800x400.png/005522?text=nature+delectus', 0, 'nemo-dolor-facere-et601ef1de91709', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(36, 3, 2, 'Harum dolorem aut et rem.', '<p>Est aut vel occaecati occaecati. Dolor minus voluptatem odio fugit quidem unde. Non necessitatibus soluta consectetur omnis. Eum aliquam omnis cumque facilis sunt et beatae. Hic deserunt eos deleniti minima tempora quo. Nostrum dolores aut nobis atque ad amet voluptatum commodi. Neque est ipsam recusandae corrupti et. Sed occaecati illum recusandae sapiente. Eos soluta officiis non qui eum. Nihil ut ullam et dolores. Quasi consequatur et adipisci atque et velit quam. Neque et expedita eaque ea. Omnis ut ut ut repudiandae fuga voluptas sed voluptatibus. Voluptatem laborum et mollitia est. Fugit dolores voluptas natus sequi. Eligendi et quas eveniet atque. Voluptates dolor ut recusandae et placeat placeat. Dolor iure quia dicta dolorum enim. Vel quia unde cum ut adipisci consequatur animi id. Dolor laboriosam neque laudantium aliquid culpa quisquam. Asperiores consequatur eius enim nemo ex voluptatem. Et quia non explicabo ipsa explicabo adipisci. Debitis voluptatibus eos omnis occaecati voluptates autem aut nobis. Voluptatem accusantium aliquid quaerat totam corrupti voluptate. Inventore ex et in deleniti dolor qui. Qui qui et sed voluptas neque odio ipsam ratione. Id repudiandae at quos nesciunt dicta aspernatur aperiam. Perspiciatis perferendis accusamus ea est reiciendis corporis. Dolore commodi culpa ipsa et. Rerum reiciendis fugit sed minima maiores atque cupiditate. Quia libero ex et error quos. Qui hic error sed consequuntur natus. Aliquam ex dolorem aliquid sed similique sequi similique. Sed fuga dolor ab. Sit magnam omnis est eligendi accusantium. Voluptatem doloremque placeat aut. Qui veniam impedit rerum possimus expedita eius. Quasi mollitia officia officiis sunt aspernatur modi et. Voluptas vero quidem laboriosam fuga quod porro corrupti. Ab suscipit autem rerum voluptatem. Ea aut possimus dolor eligendi placeat. Quia voluptas ut sit reiciendis odio. Quis est quidem eos ut et cupiditate voluptatem. Quis non et occaecati molestiae sit quasi dolore.</p>', 'https://via.placeholder.com/800x400.png/00ddee?text=nature+rem', 0, 'harum-dolorem-aut-et-rem601ef1de93200', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(37, 1, 8, 'Tempore tempora optio qui expedita qui aut.', '<p>Atque sit eveniet est doloribus eligendi animi. Iure et sed fugiat voluptatem totam sunt iusto. Ut doloremque doloribus aut commodi. Ab aut odit dolor. A non officia soluta tempora voluptas beatae quos. Ipsa nisi blanditiis delectus voluptatem deserunt rem. Ut quibusdam qui dolor adipisci excepturi optio itaque. Iste mollitia quia esse explicabo sit facilis. Mollitia sit ipsum nihil aut iure. Occaecati consectetur aut nihil sunt numquam voluptatem. Exercitationem qui minus necessitatibus voluptatem. At possimus corporis voluptatem nam ea modi sunt corporis. Ut perspiciatis voluptatem est laboriosam. Placeat distinctio vel molestiae quibusdam. Maxime similique facilis et magni aut. In dicta voluptas et amet animi unde sit. Modi voluptatem distinctio alias. Velit quaerat et et commodi eos vel praesentium. Harum distinctio hic ratione. Et voluptatem consequatur possimus sed facere earum. Eum quos sed voluptates excepturi. Amet deserunt odit cumque quo id. Neque ipsa et temporibus omnis voluptate et est. Mollitia ad quia adipisci vitae est ab ad. Reiciendis aut voluptas rerum ratione ut quis. Dolor dolore et qui libero. Iure fugiat asperiores voluptate corrupti doloribus reiciendis ab. Debitis exercitationem blanditiis voluptatem qui quia quia. Libero facere sit aut qui. Rem a consequatur nemo rerum voluptatum perspiciatis. Ut magni incidunt dolorum aliquid. Odio quo totam labore vitae vero ipsum recusandae. Dignissimos vero et vero. Consequatur corrupti amet eaque molestias harum ut ad cum. Aut incidunt qui quibusdam. Iusto possimus harum cupiditate nobis aut. Excepturi repellat sed adipisci impedit rerum eos aliquam. Illo qui velit in neque veniam saepe. Asperiores delectus repellendus nulla est commodi quia quo. Est necessitatibus et possimus nihil sunt et. Magni sit sed totam esse corrupti.</p>', 'https://via.placeholder.com/800x400.png/008833?text=nature+provident', 0, 'tempore-tempora-optio-qui-expedita-qui-aut601ef1de943df', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(38, 3, 3, 'Et nam omnis eum voluptatibus sequi odit.', '<p>Harum consequatur sed debitis et rerum tempore. Consequatur excepturi repellendus molestiae ut blanditiis nostrum. Ratione quod recusandae non iste dolorem exercitationem. Amet exercitationem ipsum sed beatae mollitia qui aliquam nam. Culpa aut commodi accusamus voluptatum repudiandae. Maxime eveniet eaque illum inventore exercitationem aliquam. Et vero perferendis qui rerum temporibus dolores excepturi quasi. Culpa itaque est nobis ipsam aut. Officiis reiciendis itaque saepe at. Ut ut expedita earum ea amet. Voluptatem impedit deserunt esse minus dolore. Numquam et velit praesentium libero at autem nemo accusantium. Occaecati voluptatum ut qui est inventore et voluptatibus. Non quia facere sed repellendus. Quam quaerat enim asperiores. Voluptas est molestiae fugiat et et aut. Eos illo ipsa sit nam doloremque atque aut. Facere laudantium vero dicta laborum vero asperiores ut dolorum. Occaecati sint tempore aut tenetur eum ut. Dicta quia aut et saepe libero. Exercitationem sequi ipsam non ratione mollitia molestias iusto quasi. Aut voluptatem voluptatum dolores ipsa iste aut. Et veniam deserunt libero rem quia. Voluptas nesciunt numquam vero debitis asperiores. Nihil quia molestiae voluptatem. Facilis facilis qui molestiae ut et est. Debitis aspernatur sapiente aliquam. Saepe voluptates aliquam adipisci modi dolor cum. Aut iure totam quisquam molestiae ab doloremque debitis. Eos perspiciatis qui excepturi. Et ab quaerat consequuntur quia ea et ex enim.</p>', 'https://via.placeholder.com/800x400.png/0022ee?text=nature+ut', 0, 'et-nam-omnis-eum-voluptatibus-sequi-odit601ef1de95629', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(39, 2, 3, 'Saepe sed qui necessitatibus porro voluptate nihil sunt laborum sit dolores.', '<p>Id et velit dolorem qui quia sed facilis praesentium. Voluptatum recusandae ipsam consequatur. Blanditiis laborum qui et quia. At illum similique et eaque commodi. Laudantium doloremque debitis incidunt a beatae enim iusto. In dolor voluptatem amet nihil quibusdam sit iste. Omnis eveniet et expedita sit excepturi. Doloremque quo velit aut ea qui. Voluptatibus sunt et voluptate placeat. Earum alias reiciendis id sed. Quibusdam incidunt asperiores numquam. Blanditiis perspiciatis aut possimus aut sapiente adipisci quidem. Provident quo rerum magnam dolorem quia sed ea. Et architecto eos fugit eos magni. Suscipit doloremque officiis porro. Qui vel nihil ea labore temporibus excepturi doloribus. Eligendi accusantium voluptas in natus deserunt optio cupiditate. Dolor voluptates suscipit est quod quo est at. Aut qui earum ut facilis maxime minus vel perferendis. Est labore sint suscipit sed sed magnam. Et nihil ut dolore quidem dolorum aut et. Reprehenderit quas dolores sequi praesentium. Qui itaque voluptas earum iure quia sed minus. Consectetur veniam ea maiores qui pariatur vitae. Aut corporis necessitatibus assumenda ut repellat. Vel deleniti deleniti in voluptatum. Et voluptatibus facere voluptatem magni. Maiores repellendus suscipit tempora soluta quaerat tempora. Tempore adipisci aspernatur expedita voluptas velit saepe autem eum. Necessitatibus voluptatem asperiores exercitationem. Natus necessitatibus est nesciunt perspiciatis nostrum hic eos a. Quos consectetur reiciendis dolores quia quo. Porro iusto rerum veritatis et. Rerum facilis rerum vero enim eos qui tempore. Molestiae sapiente quia veniam praesentium corrupti aliquam sit ut. Non magnam veniam perferendis. Repellat aut et praesentium tempora. Quo suscipit illo assumenda a consequatur. Aspernatur eos quam inventore sit. Ipsam dolores maiores qui mollitia. Voluptatem fuga nam quae qui. Non dolorem aut rerum laudantium nostrum. Odio voluptas non et in laboriosam non. Et vero magnam eos itaque aut atque repellendus. Voluptas vel quis nihil quasi. Nihil quod asperiores non tempora non. Eum quis libero odit modi deleniti.</p>', 'https://via.placeholder.com/800x400.png/009911?text=nature+molestias', 0, 'saepe-sed-qui-necessitatibus-porro-voluptate-nihil-sunt-laborum-sit-dolores601ef1de966a6', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(40, 5, 9, 'Sequi voluptas corrupti aut inventore.', '<p>Laborum animi repellat est ea aut et. Dolores cumque ut perferendis possimus quis et. Voluptatum possimus non perferendis debitis voluptate. Qui asperiores esse officia et harum vitae. Ipsa et qui magnam occaecati nobis rem. Enim corrupti minus vel possimus. Eum et in et beatae fugiat dolore eum. Ipsa repellat omnis earum tenetur ut qui. Omnis quia esse amet iure asperiores numquam praesentium sequi. Dignissimos sequi voluptatem quisquam iste. Sed quo eos qui sint suscipit nulla. Velit est assumenda illum veniam autem dolorem id rerum. Dolore ab earum ut. Aliquam dignissimos odio accusantium minima impedit. Rerum quibusdam quo dolor non officiis voluptatibus quis. Quisquam dolor nam molestiae perspiciatis et laborum consectetur. Aut et possimus odit consectetur iure. Magnam et et fugiat ea laudantium. Cupiditate tenetur aliquam tempore fugiat optio aut omnis. Necessitatibus id minima eum. Optio voluptas enim sed. A alias possimus dolores earum dolores aspernatur quisquam. Sunt aut quaerat et id architecto. Dolor qui fugiat et magnam ducimus et. Magnam aut quia sint qui ab laborum provident dignissimos. Beatae aliquid nam corrupti ducimus doloremque. Facere distinctio omnis libero. Atque veniam eius fugiat nostrum est dolore. Asperiores quibusdam molestiae omnis. Delectus sed et animi occaecati. Possimus at odit sed iusto sint. Placeat quia eum magni iste ipsam qui. Molestias in fuga voluptatum cupiditate omnis ex. Eaque quia quas similique. Aspernatur aut et error fugit iste non. Occaecati autem asperiores minus dolorum et. Iusto repudiandae repudiandae consequatur repellendus ipsum voluptas. Aut ea ab voluptate modi possimus. Sint omnis nam ratione sed nihil ut eius. Et magnam mollitia eaque et.</p>', 'https://via.placeholder.com/800x400.png/00cc00?text=nature+sit', 0, 'sequi-voluptas-corrupti-aut-inventore601ef1de9769b', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(41, 5, 3, 'Est aut nisi quae eum ipsum et quos.', '<p>A voluptate at harum voluptatem animi dolor. Quidem in aliquid nihil. Eaque nemo nam voluptates blanditiis nisi neque ut. Doloremque sunt aut ullam cum. Soluta ullam sit quos ullam. Distinctio nobis doloremque aspernatur rem nulla fuga culpa. Eius eos sunt qui sint laborum voluptatem. Culpa unde adipisci iusto voluptas atque. Iure et sequi non molestias sapiente. Sed sed nam nostrum ut consequatur eos dolorem. Et ex possimus similique eius. Tempore facilis culpa sed iusto illum sed. Veritatis expedita numquam dolores deserunt. Eum quidem voluptate maiores aut facere tenetur fugiat numquam. Aperiam adipisci placeat eum voluptatem ut. Voluptatem ipsa et quis qui atque quaerat vitae sit. Culpa aut et in sint culpa. Mollitia nihil enim odit iusto voluptate suscipit. Eveniet hic et ipsum sint. Nesciunt quibusdam omnis ut commodi laudantium voluptas. Doloremque molestias rerum voluptatem dicta. Delectus officiis nam est. Eaque id quos aliquid quibusdam autem. Reprehenderit enim quisquam dolores facilis. Et culpa ut totam commodi magnam. Impedit quis quam sunt at. Asperiores quo et et eos. Sed odio in tempore sed velit id. Placeat qui quia id explicabo doloribus. Praesentium velit maxime aut optio sunt eveniet et. Repudiandae dolorum voluptas inventore velit ut voluptatem. Quisquam est laudantium sed consectetur odit. Nam ipsa sapiente aut ut animi id. Animi a dicta sint facilis eum reprehenderit. Suscipit modi et inventore eveniet inventore.</p>', 'https://via.placeholder.com/800x400.png/001199?text=nature+amet', 0, 'est-aut-nisi-quae-eum-ipsum-et-quos601ef1de985aa', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(42, 1, 9, 'Exercitationem in qui qui blanditiis beatae et illo veniam vel.', '<p>Molestias dolorem architecto porro expedita. Et velit natus perspiciatis et eum tempore. Dicta iure id tempore quasi necessitatibus adipisci sint. Sunt adipisci ipsam quae accusamus et amet est a. Numquam adipisci consequuntur odio reiciendis. Repellendus omnis nulla omnis est. Quia ut iusto similique aperiam perspiciatis rerum in ducimus. Est aspernatur id illum sint eius ut officiis accusamus. At aperiam delectus non doloribus eligendi ut atque tempora. Ipsum quo atque molestias sed. Error laborum rerum animi quas et tenetur. Accusantium sint quasi tempore harum amet quo. Sequi eligendi magnam unde magni est dolor ut. Rerum voluptas ipsum eos et dolorem voluptas. Tempore quae vel maiores impedit occaecati reiciendis corporis. Rem ea vel nihil ullam id ipsum et. Delectus eveniet alias nobis. Et voluptas eos vitae et aperiam quia. Odit aut non dolorum quae animi nostrum. Sit earum tenetur voluptas praesentium et. Molestiae ea atque vel qui nemo facere quis vel. Commodi placeat in quae cupiditate.</p>', 'https://via.placeholder.com/800x400.png/0022ee?text=nature+repudiandae', 0, 'exercitationem-in-qui-qui-blanditiis-beatae-et-illo-veniam-vel601ef1de99353', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(43, 3, 3, 'Aut voluptas et porro optio velit enim vitae.', '<p>Enim eum nihil quo tempore perspiciatis qui. Voluptas occaecati laborum repudiandae. Corporis quis quidem incidunt sequi aspernatur ut. Qui rerum ut sequi delectus. Et iusto sunt modi enim illum. Ipsam et eos dolorem. Reiciendis nisi et doloremque et amet aut. Nihil velit aut id quia hic natus rerum. Et necessitatibus dolor quos nostrum dolorum et. Quia dolores ad dolorem quia odit nam dolores. Aut rerum dolor ea odio. Reprehenderit rerum qui commodi tempore quaerat corporis et. Totam quia debitis doloremque magnam modi deserunt. Officia repellendus provident dolor illo voluptatibus dolores. Officia minus iure aut vero quia nihil. Nihil ducimus saepe sunt quia reiciendis et animi. Ab beatae aut est qui expedita qui officiis sint. Aperiam voluptate consequatur ipsum voluptas. Et maiores sed omnis enim. Soluta quisquam non doloremque sequi ex modi repudiandae. Exercitationem recusandae id ex ipsum mollitia. Neque aliquam placeat rem voluptas enim. Vero veritatis quisquam ut. Harum rerum expedita fuga quidem praesentium. Rem cupiditate suscipit corporis pariatur nulla unde et laborum. Sed laborum consequuntur enim quo vel. Architecto quidem veritatis quia assumenda et id. Laudantium fuga minus recusandae sit enim. Officia asperiores consequuntur ducimus magnam adipisci dignissimos at. Culpa enim velit molestias id ea. Id consequatur reiciendis voluptatum consequuntur nobis accusantium. Quaerat modi unde nobis laborum ducimus nobis. Porro distinctio dolorem et asperiores. Ipsum facilis sit neque quisquam aut fuga. Non nam vitae magnam aperiam quis autem et. Maxime impedit dicta ut sit. Dolorum sequi minima aut. Iure perferendis occaecati quia qui. Harum unde voluptatum aut provident labore ut. Dolor repellendus repellendus distinctio in et cupiditate quas. Nobis fuga non pariatur quia eius nihil temporibus. Ut laboriosam et beatae reprehenderit eum saepe quod. Error doloribus doloremque eum vitae voluptas modi totam. Sunt et nobis ut excepturi ex voluptatem eos nesciunt. Eaque dignissimos architecto et ullam iure perspiciatis. Minus qui reprehenderit ipsa perferendis temporibus praesentium.</p>', 'https://via.placeholder.com/800x400.png/004477?text=nature+et', 0, 'aut-voluptas-et-porro-optio-velit-enim-vitae601ef1de9ad56', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(44, 4, 8, 'Non voluptas fuga est.', '<p>Quasi aut velit iste optio quaerat nostrum. Rerum sequi et voluptas sunt et. Aut sequi et ut atque aut molestiae. Voluptas sit expedita repellat laudantium. Aliquam facere dolorem id dolor. Quo animi natus quas repudiandae voluptate culpa dolorem. Eaque ut ipsa dolores voluptatem et autem voluptates in. Et minus illum et voluptates error omnis. Sunt expedita eius et temporibus consequatur. Est iste sequi id est laudantium nesciunt. Laboriosam quidem laudantium nemo possimus aut impedit. Et delectus qui adipisci omnis. Quisquam pariatur eum natus fugit. Minima non quaerat ea dolore dolore. Atque quisquam iure ut ex delectus et quam. Earum unde placeat eum numquam id officiis ipsam dolor. Et voluptas est sint. Atque dolore asperiores dolorem. Consequatur excepturi ab commodi aut quasi. Qui sit quisquam numquam natus in ullam necessitatibus. Dicta sed dolorem ab ea incidunt reprehenderit. Dicta et distinctio deleniti est reprehenderit quaerat reiciendis. Est ducimus aliquam assumenda. Expedita consequatur dicta in adipisci. Consectetur est ipsam rerum ut quis eligendi. Totam at non suscipit ut unde ad. Aut est dolor cupiditate accusamus qui atque. Quam ut est velit beatae soluta nostrum. Et in earum voluptatem. Excepturi repellendus deleniti perspiciatis qui natus commodi illo voluptas. Error ad ea consequatur inventore eveniet omnis qui. Eveniet tempore maxime natus mollitia nihil rem. Laboriosam ipsum consequatur sed et deserunt in. Doloremque est omnis ratione sunt optio maxime porro ratione. Rerum aut cum quis voluptatem qui nihil consequatur vel. Eveniet qui ut temporibus sed aut perspiciatis sunt officia. Eum repudiandae minus accusamus facere eos at. Dolore voluptatem maxime asperiores maxime. Vel pariatur nemo deleniti molestiae. Quia quidem esse rerum similique ipsum et accusantium. Beatae non eveniet at totam accusantium rerum.</p>', 'https://via.placeholder.com/800x400.png/009911?text=nature+quas', 0, 'non-voluptas-fuga-est601ef1de9bc9a', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(45, 2, 4, 'Vel illum aspernatur voluptatibus.', '<p>Quas nam nesciunt totam quos repellat optio. Dolore molestiae assumenda autem omnis. Nesciunt unde perspiciatis numquam in ex distinctio in quis. Molestiae culpa aspernatur qui fuga quia rerum. Corrupti voluptatem explicabo perferendis dolores at quia reiciendis. Voluptate aut quia est. Quis expedita qui error. Quibusdam illo voluptatem ex quas sint hic. Itaque nesciunt qui ab explicabo aut. Aut ut non et in est. Ipsam id sint ut suscipit reprehenderit quo quam. Id quos et exercitationem vel. Nesciunt delectus perspiciatis eveniet fugit dicta. Expedita in recusandae vitae ratione magni voluptatem ad. Placeat eaque consequatur numquam alias et ut mollitia at. Totam praesentium qui facere autem. Dolor voluptatibus ut et nihil modi. Similique reprehenderit nisi sit. Omnis id autem voluptas quia laudantium. Placeat similique labore vel ab ipsam illo. Cupiditate ut ea aut asperiores officiis commodi rerum. Debitis magnam qui omnis similique. Error molestiae nisi enim perferendis autem esse fugit. Dolor sed aut quia dolorem sunt. Quaerat ipsam rerum soluta qui. Eos et sit voluptatem facere perspiciatis distinctio aliquid. Rerum animi quis ut veniam sit. Quia nam quas numquam et et possimus amet reiciendis. Et in perspiciatis excepturi nemo enim. Omnis placeat quisquam assumenda sit minus quis provident. Rerum minus quo ut maxime mollitia. Voluptate expedita veritatis quaerat est illum iure eligendi. Velit excepturi et cumque. Consequatur labore architecto reiciendis sequi iste rerum nobis quo. Maxime qui unde aut voluptatem molestiae. Quia molestias ipsa omnis similique. Accusantium ipsum dolorem quia architecto pariatur sunt sequi. Recusandae maxime repellendus esse est qui deserunt. Dolores beatae officia sint ea dolores aut. Facere est sunt non quas excepturi.</p>', 'https://via.placeholder.com/800x400.png/0022bb?text=nature+ut', 0, 'vel-illum-aspernatur-voluptatibus601ef1de9cb3f', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(46, 1, 1, 'Deneme Başlık', '<p>Bu makale Deneme Makalesidir.</p>', 'uploads/img/601fdbfaa1f34anna-0n0AHB1fgTQ-unsplash.jpg', 0, 'deneme-baslik', '2021-02-07 09:24:26', '2021-02-07 09:24:26'),
(49, 1, 8, 'Spor', '<p><b><u>Sipey&nbsp;</u></b><u style=\"font-weight: bolder; font-size: 1rem;\">Sipey&nbsp;</u><u style=\"font-weight: bolder; font-size: 1rem;\">Sipey</u></p>', 'uploads/img/60212a34b4a66daniel-tong-xBeid9r1paU-unsplash.jpg', 0, 'spor', '2021-02-08 09:10:28', '2021-02-08 09:13:34');

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `categories`
--

CREATE TABLE `categories` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Tablo döküm verisi `categories`
--

INSERT INTO `categories` (`id`, `name`, `slug`, `created_at`, `updated_at`) VALUES
(1, 'Bilim', 'bilim601ef1de9da18', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(2, 'Teknoloji', 'teknoloji601ef1de9e81c', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(3, 'Yazılım', 'yazilim601ef1de9f249', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(4, 'Uzay', 'uzay601ef1de9fb2f', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(5, 'Gelecek', 'gelecek601ef1dea040b', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(6, 'Tarih', 'tarih601ef1dea0c98', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(7, 'Evrim', 'evrim601ef1dea1551', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(8, 'Sağlık', 'saglik601ef1dea1d57', '2021-02-06 19:45:34', '2021-02-06 19:45:34'),
(9, 'Yaşam', 'yasam601ef1dea24b3', '2021-02-06 19:45:34', '2021-02-06 19:45:34');

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `contacts`
--

CREATE TABLE `contacts` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `firstName` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `lastName` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `Subject` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `Message` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `Flag` int(11) NOT NULL DEFAULT 0,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Tablo döküm verisi `contacts`
--

INSERT INTO `contacts` (`id`, `firstName`, `lastName`, `Subject`, `email`, `Message`, `Flag`, `created_at`, `updated_at`) VALUES
(1, 'Yunus', 'Kaya', 'Deneme', 'yk.kayayunus@gmail.com', 'Merhaba Dünya bu aralar nasılsın.', 1, '2021-02-07 10:09:15', '2021-02-07 16:44:31'),
(2, 'Yunus', 'Kaya', '2. Deneme Mesajı', '34yunuskaya@gmail.com', 'Deneme Mesajı 2', 0, '2021-02-07 11:51:27', '2021-02-07 11:51:27'),
(3, 'Eyüp', 'Kaya', '3. Deneme Mesajı', 'amiya41@hotmail.com', 'asdasdassdasgvrwefvdggewdasfg', 1, '2021-02-07 13:41:32', '2021-02-07 16:41:45'),
(4, 'Lütfi', 'Bak', 'Alım Satım', 'amiya@hotmail.com', 'Alım SatımAlım SatımAlım SatımAlım Satım', 0, '2021-02-07 13:43:56', '2021-02-07 16:44:46'),
(5, 'Halil', 'Kaya', 'Deneme', 'amiya41@hotmail.com', 'Deneme Mesajı', 0, '2021-02-08 09:07:52', '2021-02-08 09:07:52');

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `migrations`
--

CREATE TABLE `migrations` (
  `id` int(10) UNSIGNED NOT NULL,
  `migration` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Tablo döküm verisi `migrations`
--

INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES
(13, '2014_10_12_000000_create_users_table', 1),
(14, '2021_02_06_125626_create_articles_table', 1),
(15, '2021_02_06_125802_create_categories_table', 1),
(16, '2021_02_07_074829_create_contacts_table', 2);

-- --------------------------------------------------------

--
-- Tablo için tablo yapısı `users`
--

CREATE TABLE `users` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `role` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'user',
  `img` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `borderimg` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `biography` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `slug` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Tablo döküm verisi `users`
--

INSERT INTO `users` (`id`, `name`, `email`, `password`, `role`, `img`, `borderimg`, `biography`, `slug`, `created_at`, `updated_at`) VALUES
(1, 'Yunus Kaya', '34yunuskaya@gmail.com', '$2y$10$Xv1XY6i3gHSkK9xQhamOYOmXglKnLLH2.R0FzMIKQHDnb4c5kEWWq', 'admin', 'uploads/profil/60200eb6d5212IMG_20191006_223953.jpg', 'uploads/profil/6021217799035natalie-cardona-W8BRzoUTHNA-unsplash.jpg', 'Occaecati earum dolores nemo facilis sunt similique. Fuga nostrum veritatis quam provident. Id sit et qui quae quia non velit. Ad neque est quasi sunt veritatis distinctio. Consectetur deleniti natus temporibus quos qui ipsa sit quo. Sed maiores occaecati quisquam ex. Inventore ratione labore temporibus reprehenderit ex dolorem qui. Distinctio et velit incidunt non rem deleniti fuga. Aperiam explicabo aut impedit. Qui neque quis ipsum repudiandae ea impedit modi. Molestiae optio nobis repudiandae ut quia. Fugit labore tenetur id ad. Tempora laboriosam ipsa laborum quia expedita neque. Et nisi placeat at dignissimos aperiam ut. Dignissimos soluta reiciendis eos laudantium. Omnis quia quas libero. Quisquam officiis provident totam optio. Beatae et maxime aliquam nam distinctio assumenda.', 'yunus-kaya60212177943f5', '2021-02-06 19:45:33', '2021-02-08 08:33:11'),
(2, 'Jadon Cummings', 'sbraun@gmail.com', '$2y$10$FiLn/OLrtlq4GdIkYY7aiOZv0I/22oJ5J79tZ1HRgKooG4q/nJOmi', 'admin', 'https://via.placeholder.com/800x800.png/004488?text=people+quae', 'https://via.placeholder.com/800x400.png/00ddbb?text=city+quo', 'Eveniet quia iure in aliquam et. Est voluptatum qui ad neque et id. Optio earum alias rerum est perferendis non iste.', 'jadon-cummings601ef1ddef8b6', '2021-02-06 19:45:33', '2021-02-07 09:13:53'),
(3, 'Lola Fadel', 'amiya41@hotmail.com', '$2y$10$Oe3NJ3BMhLOON0U6wg8npuVS6Yc/.NGgPGCYvV1W/p2PuiqPeQERa', 'admin', 'https://via.placeholder.com/800x800.png/0011bb?text=people+commodi', 'https://via.placeholder.com/800x400.png/006655?text=city+in', 'Aut et ex voluptas quia repellendus. Modi id ipsa atque. Consequatur itaque earum sed et consequuntur laboriosam ipsa.', 'lola-fadel601ef1de117d3', '2021-02-06 19:45:34', '2021-02-07 09:13:53'),
(4, 'Gaston Kilback', 'rgerhold@gmail.com', '$2y$10$HHEphiBQBVQkHKEZokN9c.0voaCBsR5gLT/j/Wm3QOD/g9YHIRwme', 'admin', 'https://via.placeholder.com/800x800.png/0044cc?text=people+temporibus', 'https://via.placeholder.com/800x400.png/0011bb?text=city+officia', 'Voluptas nihil labore sit aut dolorem doloremque. Nam cum placeat enim fuga voluptatem. Dolorem sequi delectus sint.', 'gaston-kilback601ef1de28acf', '2021-02-06 19:45:34', '2021-02-07 09:13:53'),
(5, 'Alva Corwin', 'vilma74@hotmail.com', '$2y$10$nU3EYI9NktOA0M40hY2ELOLy7a4AKuU3KBaKXKFSQQeRLxWkpvzSe', 'admin', 'https://via.placeholder.com/800x800.png/0033dd?text=people+possimus', 'https://via.placeholder.com/800x400.png/00ffbb?text=city+sequi', 'Laborum quaerat aut necessitatibus harum. Molestiae commodi cumque maiores.', 'alva-corwin601ef1de3f4c7', '2021-02-06 19:45:34', '2021-02-07 09:13:53'),
(6, 'Kailee Cole', 'nlubowitz@hotmail.com', '$2y$10$BrmdajrnAKeb.hJ4z3m3Mub9gJ9KPuUST/zL0lcGanXraffysHN6m', 'admin', 'https://via.placeholder.com/800x800.png/00dddd?text=people+et', 'https://via.placeholder.com/800x400.png/003399?text=city+qui', 'Atque quidem sunt quia vero est voluptate. Atque ipsa repellendus qui eum. Voluptatem pariatur labore alias eum.', 'kailee-cole601ef1de55931', '2021-02-06 19:45:34', '2021-02-07 09:13:53'),
(7, 'Maximus Purdy', 'qhamill@hotmail.com', '$2y$10$4jWfGs4Llk4b439JYHJgDORTqTnQ1RtOwDl8aO.Iw7tuk8thbiwNe', 'admin', 'https://via.placeholder.com/800x800.png/00bb00?text=people+rerum', 'https://via.placeholder.com/800x400.png/0099ff?text=city+veniam', 'Numquam velit optio sint in molestiae sunt. Suscipit qui natus repellendus cupiditate et. Omnis autem quis ut consequuntur recusandae omnis enim qui.', 'maximus-purdy601ef1de6cd14', '2021-02-06 19:45:34', '2021-02-07 09:13:53');

--
-- Dökümü yapılmış tablolar için indeksler
--

--
-- Tablo için indeksler `articles`
--
ALTER TABLE `articles`
  ADD PRIMARY KEY (`id`);

--
-- Tablo için indeksler `categories`
--
ALTER TABLE `categories`
  ADD PRIMARY KEY (`id`);

--
-- Tablo için indeksler `contacts`
--
ALTER TABLE `contacts`
  ADD PRIMARY KEY (`id`);

--
-- Tablo için indeksler `migrations`
--
ALTER TABLE `migrations`
  ADD PRIMARY KEY (`id`);

--
-- Tablo için indeksler `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- Dökümü yapılmış tablolar için AUTO_INCREMENT değeri
--

--
-- Tablo için AUTO_INCREMENT değeri `articles`
--
ALTER TABLE `articles`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=50;

--
-- Tablo için AUTO_INCREMENT değeri `categories`
--
ALTER TABLE `categories`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=14;

--
-- Tablo için AUTO_INCREMENT değeri `contacts`
--
ALTER TABLE `contacts`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- Tablo için AUTO_INCREMENT değeri `migrations`
--
ALTER TABLE `migrations`
  MODIFY `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=17;

--
-- Tablo için AUTO_INCREMENT değeri `users`
--
ALTER TABLE `users`
  MODIFY `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
